#!/usr/bin/env python3

###
# Generates build files for the project.
# This file also includes the project configuration,
# such as compiler flags and the object matching status.
#
# Usage:
#   python3 configure.py
#   ninja
#
# Append --help to see available options.
###

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

from tools.project import (
    Object,
    ProjectConfig,
    calculate_progress,
    generate_build,
    is_windows,
)

# Game versions
DEFAULT_VERSION = 0
VERSIONS = [
    "G8ME01",  # 0
]

parser = argparse.ArgumentParser()
parser.add_argument(
    "mode",
    choices=["configure", "progress"],
    default="configure",
    help="script mode (default: configure)",
    nargs="?",
)
parser.add_argument(
    "-v",
    "--version",
    choices=VERSIONS,
    type=str.upper,
    default=VERSIONS[DEFAULT_VERSION],
    help="version to build",
)
parser.add_argument(
    "--build-dir",
    metavar="DIR",
    type=Path,
    default=Path("build"),
    help="base build directory (default: build)",
)
parser.add_argument(
    "--binutils",
    metavar="BINARY",
    type=Path,
    help="path to binutils (optional)",
)
parser.add_argument(
    "--compilers",
    metavar="DIR",
    type=Path,
    help="path to compilers (optional)",
)
parser.add_argument(
    "--map",
    action="store_true",
    help="generate map file(s)",
)
parser.add_argument(
    "--debug",
    action="store_true",
    help="build with debug info (non-matching)",
)
if not is_windows():
    parser.add_argument(
        "--wrapper",
        metavar="BINARY",
        type=Path,
        help="path to wibo or wine (optional)",
    )
parser.add_argument(
    "--dtk",
    metavar="BINARY | DIR",
    type=Path,
    help="path to decomp-toolkit binary or source (optional)",
)
parser.add_argument(
    "--objdiff",
    metavar="BINARY | DIR",
    type=Path,
    help="path to objdiff-cli binary or source (optional)",
)
parser.add_argument(
    "--sjiswrap",
    metavar="EXE",
    type=Path,
    help="path to sjiswrap.exe (optional)",
)
parser.add_argument(
    "--verbose",
    action="store_true",
    help="print verbose output",
)
parser.add_argument(
    "--non-matching",
    dest="non_matching",
    action="store_true",
    help="builds equivalent (but non-matching) or modded objects",
)
args = parser.parse_args()

config = ProjectConfig()
config.version = str(args.version)
version_num = VERSIONS.index(config.version)

# Apply arguments
config.build_dir = args.build_dir
config.dtk_path = args.dtk
config.objdiff_path = args.objdiff
config.binutils_path = args.binutils
config.compilers_path = args.compilers
config.debug = args.debug
config.generate_map = args.map
config.non_matching = args.non_matching
config.sjiswrap_path = args.sjiswrap
if not is_windows():
    config.wrapper = args.wrapper
# Don't build asm unless we're --non-matching
if not config.non_matching:
    config.asm_dir = None

# Tool versions
config.binutils_tag = "2.42-1"
config.compilers_tag = "20240706"
config.dtk_tag = "v0.9.4"
config.objdiff_tag = "v2.0.0-beta.3"
config.sjiswrap_tag = "v1.1.1"
config.wibo_tag = "0.6.11"

# Project
config.config_path = Path("config") / config.version / "config.yml"
config.check_sha_path = Path("config") / config.version / "build.sha1"
config.asflags = [
    "-mgekko",
    "--strip-local-absolute",
    "-I include",
    f"-I build/{config.version}/include",
    f"--defsym version={version_num}",
]
config.ldflags = [
    "-fp hardware",
    "-nodefaults",
    "-W off",
]

# Base flags, common to most GC/Wii games.
# Generally leave untouched, with overrides added below.
cflags_base = [
    # define the platform
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    # for multibyte
    "-multibyte",
    "-char unsigned",
    # platform specific
    "-fp hardware",
    "-Cpp_exceptions off",
    '-pragma "cats off"',
    # default compiler flags
    "-W all",
    "-O4,s",
    '-pragma "warn_notinlined off"',
    # helpful linking stuff
    "-maxerrors 1",
    "-nosyspath",
    # dtk-specific includes
    "-i include",
    f"-i build/{config.version}/include",
    f"-DVERSION={version_num}",
]

# Debug flags
if config.debug:
    cflags_base.extend(["-sym on", "-DDEBUG=1"])
else:
    cflags_base.extend(["-sym on", "-DNDEBUG=1"])

# Metrowerks library flags
cflags_runtime = [
    *cflags_base,
    "-use_lmw_stmw on",
    "-str reuse,pool,readonly",
    "-gccinc",
    "-common off",
    "-inline auto",
]

# Game-specific flags
cflags_static = [
    *cflags_base,
    "-fp_contract on",
    "-use_lmw_stmw on",
    "-rostr",
    "-inline deferred",
    "-sdata 48",
    "-sdata2 6",
    "-w nonotused",
    "-once",
]

# REL flags
cflags_rel = [
    *cflags_base,
    "-fp_contract on",
    "-use_lmw_stmw on",
    "-rostr",
    "-inline auto,deferred",
    "-sdata 0",
    "-sdata2 0",
    "-w nonotused",
    "-once",
    "-i include/rel",
]

config.linker_version = "GC/2.6"


# Helper function for Dolphin libraries
def DolphinLib(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.3.2",
        "cflags": cflags_base,
        "host": False,
        "objects": objects,
    }


# Helper function for REL script objects
def Rel(lib_name: str, src_dir: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/2.6",
        "cflags": cflags_rel,
        "host": False,
        "src_dir": src_dir,
        "objects": objects,
    }


Matching = True
NonMatching = False

config.warn_missing_config = False
config.warn_missing_source = False
config.libs = [
    {
        "lib": "Runtime.PPCEABI.H",
        "mw_version": config.linker_version,
        "cflags": cflags_runtime,
        "host": False,
        "objects": [
            Object(NonMatching, "Runtime.PPCEABI.H/global_destructor_chain.c"),
        ],
    },
    {
        "lib": "MarioSt",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "cam_road.c"),
            Object(NonMatching, "cam_shift.c"),
            Object(NonMatching, "countdown.c"),
            Object(NonMatching, "database.c"),
            Object(NonMatching, "event.c"),
            Object(NonMatching, "gxsub.c"),
            Object(NonMatching, "himo.c"),
            Object(NonMatching, "mail_data.c"),
            Object(Matching, "main.c"),
            Object(NonMatching, "mapdata.c"),
            Object(NonMatching, "memory.c"),
            Object(NonMatching, "nameent.c"),
            Object(NonMatching, "npc_data.c"),
            Object(NonMatching, "npc_event.c"),
            Object(NonMatching, "parse.c"),
            Object(NonMatching, "peach.c"),
            Object(NonMatching, "pmario_sound.c"),
            Object(NonMatching, "romfont.c"),
            Object(NonMatching, "seqdef.c"),
            Object(NonMatching, "sound.c"),
            Object(NonMatching, "statuswindow.c"),
            Object(NonMatching, "system.c"),
            Object(NonMatching, "unk_0x8025DE70.c"),
            Object(NonMatching, "unk_0x803AE790.c"),
            Object(NonMatching, "unk_0x803B9540.c"),
        ],
    },
    {
        "lib": "sdk_custom",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "sdk/arc.c"),
            Object(NonMatching, "sdk/DEMOInit.c"),
            Object(NonMatching, "sdk/DEMOPad.c"),
            Object(NonMatching, "sdk/texPalette.c"),
        ],
    },
    {
        "lib": "action_commands",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "action/ac_air_gauge.c"),
            Object(NonMatching, "action/ac_button_down.c"),
            Object(NonMatching, "action/ac_crane_timing.c"),
            Object(NonMatching, "action/ac_gauge_timing.c"),
            Object(NonMatching, "action/ac_gauge_timing2.c"),
            Object(NonMatching, "action/ac_lst_rc_keep.c"),
            Object(NonMatching, "action/ac_monosiri_target.c"),
            Object(NonMatching, "action/ac_pendulum_crane_timing.c"),
            Object(NonMatching, "action/ac_power_gauge.c"),
            Object(NonMatching, "action/ac_power_gauge_lv.c"),
            Object(NonMatching, "action/ac_power_gauge_lv2.c"),
            Object(NonMatching, "action/ac_repeatedly.c"),
            Object(NonMatching, "action/ac_repeatedly_lv.c"),
            Object(NonMatching, "action/ac_shot.c"),
            Object(NonMatching, "action/ac_shot_target.c"),
            Object(NonMatching, "action/ac_signal_timing.c"),
            Object(NonMatching, "action/ac_stick_keep_left.c"),
            Object(NonMatching, "action/ac_stick_rotate.c"),
            Object(NonMatching, "action/ac_table.c"),
            Object(NonMatching, "action/ac_timing_a.c"),
            Object(NonMatching, "action/ac_timing_wide.c"),
        ],
    },
    {
        "lib": "star_action_commands",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "action/star/sac_bakugame.c"),
            Object(NonMatching, "action/star/sac_common.c"),
            Object(NonMatching, "action/star/sac_deka.c"),
            Object(NonMatching, "action/star/sac_genki.c"),
            Object(NonMatching, "action/star/sac_muki.c"),
            Object(NonMatching, "action/star/sac_scissor.c"),
            Object(NonMatching, "action/star/sac_suki.c"),
            Object(NonMatching, "action/star/sac_zubastar.c"),
        ],
    },
    {
        "lib": "battle",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "battle/battle.c"),
            Object(NonMatching, "battle/battle_ac.c"),
            Object(NonMatching, "battle/battle_ac_help.c"),
            Object(NonMatching, "battle/battle_acrobat.c"),
            Object(NonMatching, "battle/battle_actrecord.c"),
            Object(NonMatching, "battle/battle_attack_audience.c"),
            Object(NonMatching, "battle/battle_audience.c"),
            Object(NonMatching, "battle/battle_audience_kind_data.c"),
            Object(NonMatching, "battle/battle_audience_kinopio.c"),
            Object(NonMatching, "battle/battle_break_slot.c"),
            Object(NonMatching, "battle/battle_camera.c"),
            Object(NonMatching, "battle/battle_damage.c"),
            Object(NonMatching, "battle/battle_database_common.c"),
            Object(NonMatching, "battle/battle_detect.c"),
            Object(NonMatching, "battle/battle_disp.c"),
            Object(NonMatching, "battle/battle_enemy_item.c"),
            Object(NonMatching, "battle/battle_event_cmd.c"),
            Object(NonMatching, "battle/battle_event_default.c"),
            Object(NonMatching, "battle/battle_event_subset.c"),
            Object(NonMatching, "battle/battle_evt_cmd.c"),
            Object(NonMatching, "battle/battle_icon.c"),
            Object(NonMatching, "battle/battle_information.c"),
            Object(NonMatching, "battle/battle_item_data.c"),
            Object(NonMatching, "battle/battle_mario.c"),
            Object(NonMatching, "battle/battle_menu_disp.c"),
            Object(NonMatching, "battle/battle_message.c"),
            Object(NonMatching, "battle/battle_monosiri.c"),
            Object(NonMatching, "battle/battle_pad.c"),
            Object(NonMatching, "battle/battle_party.c"),
            Object(NonMatching, "battle/battle_seq.c"),
            Object(NonMatching, "battle/battle_seq_command.c"),
            Object(NonMatching, "battle/battle_seq_end.c"),
            Object(NonMatching, "battle/battle_stage.c"),
            Object(NonMatching, "battle/battle_stage_object.c"),
            Object(NonMatching, "battle/battle_status_effect.c"),
            Object(NonMatching, "battle/battle_status_icon.c"),
            Object(NonMatching, "battle/battle_sub.c"),
            Object(NonMatching, "battle/battle_unit.c"),
            Object(NonMatching, "battle/battle_unit_event.c"),
            Object(NonMatching, "battle/battle_weapon_power.c"),
        ],
    },
    {
        "lib": "bowser",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "bowser/koopa.c"),
            Object(NonMatching, "bowser/koopa_hit.c"),
            Object(NonMatching, "bowser/koopa_motion.c"),
            Object(NonMatching, "bowser/kpa_act.c"),
        ],
    },
    {
        "lib": "data",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(Matching, "data/item_data.c"),
        ],
    },
    {
        "lib": "driver",
        "mw_version": config.linker_version,
        "cflags": [*cflags_static, "-O4,p"],  # ???
        "host": False,
        "objects": [
            Object(NonMatching, "driver/animdrv.c"),
            Object(Matching, "driver/arcdrv.c"),
            Object(NonMatching, "driver/bgdrv.c"),
            Object(NonMatching, "driver/camdrv.c"),
            Object(NonMatching, "driver/casedrv.c"),
            Object(NonMatching, "driver/dispdrv.c"),
            Object(NonMatching, "driver/effdrv.c"),
            Object(NonMatching, "driver/envdrv.c"),
            Object(NonMatching, "driver/extdrv.c"),
            Object(NonMatching, "driver/fadedrv.c"),
            Object(NonMatching, "driver/hitdrv.c"),
            Object(NonMatching, "driver/icondrv.c"),
            Object(NonMatching, "driver/imgdrv.c"),
            Object(NonMatching, "driver/itemdrv.c"),
            Object(NonMatching, "driver/lightdrv.c"),
            Object(NonMatching, "driver/mapdrv.c"),
            Object(NonMatching, "driver/mobjdrv.c"),
            Object(NonMatching, "driver/msgdrv.c"),
            Object(NonMatching, "driver/npcdrv.c"),
            Object(NonMatching, "driver/offscreendrv.c"),
            Object(NonMatching, "driver/seqdrv.c"),
            Object(NonMatching, "driver/shadowdrv.c"),
            Object(NonMatching, "driver/swdrv.c"),
            Object(NonMatching, "driver/windowdrv.c"),
        ],
    },
    {
        "lib": "effect",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "effect/eff_batfukidashi.c"),
            Object(NonMatching, "effect/eff_batten.c"),
            Object(NonMatching, "effect/eff_bomb.c"),
            Object(NonMatching, "effect/eff_break.c"),
            Object(NonMatching, "effect/eff_breath_fire.c"),
            Object(NonMatching, "effect/eff_butterfly.c"),
            Object(NonMatching, "effect/eff_charge.c"),
            Object(NonMatching, "effect/eff_confetti.c"),
            Object(NonMatching, "effect/eff_damage_star.c"),
            Object(NonMatching, "effect/eff_energy.c"),
            Object(NonMatching, "effect/eff_fall.c"),
            Object(NonMatching, "effect/eff_fire.c"),
            Object(NonMatching, "effect/eff_fukidashi.c"),
            Object(NonMatching, "effect/eff_funemizu.c"),
            Object(NonMatching, "effect/eff_gonbaba_breath.c"),
            Object(NonMatching, "effect/eff_hibashira.c"),
            Object(NonMatching, "effect/eff_hit.c"),
            Object(NonMatching, "effect/eff_ibuki.c"),
            Object(NonMatching, "effect/eff_ice.c"),
            Object(NonMatching, "effect/eff_indirect.c"),
            Object(NonMatching, "effect/eff_irekaeru.c"),
            Object(NonMatching, "effect/eff_itemget.c"),
            Object(NonMatching, "effect/eff_kemuri.c"),
            Object(NonMatching, "effect/eff_kemutest.c"),
            Object(NonMatching, "effect/eff_kiss.c"),
            Object(NonMatching, "effect/eff_las_mon.c"),
            Object(NonMatching, "effect/eff_laser.c"),
            Object(NonMatching, "effect/eff_levelup.c"),
            Object(NonMatching, "effect/eff_machinegun.c"),
            Object(NonMatching, "effect/eff_mahojin.c"),
            Object(NonMatching, "effect/eff_mahorn.c"),
            Object(NonMatching, "effect/eff_mahorn2.c"),
            Object(NonMatching, "effect/eff_majinai.c"),
            Object(NonMatching, "effect/eff_mario_balloon.c"),
            Object(NonMatching, "effect/eff_minigame.c"),
            Object(NonMatching, "effect/eff_miss_star.c"),
            Object(NonMatching, "effect/eff_mist.c"),
            Object(NonMatching, "effect/eff_mist2.c"),
            Object(NonMatching, "effect/eff_mizutama.c"),
            Object(NonMatching, "effect/eff_mobj_broken.c"),
            Object(NonMatching, "effect/eff_mugi.c"),
            Object(NonMatching, "effect/eff_naniga.c"),
            Object(NonMatching, "effect/eff_nice.c"),
            Object(NonMatching, "effect/eff_nokotarou.c"),
            Object(NonMatching, "effect/eff_nozle.c"),
            Object(NonMatching, "effect/eff_number.c"),
            Object(NonMatching, "effect/eff_particle.c"),
            Object(NonMatching, "effect/eff_peach_fukidashi.c"),
            Object(NonMatching, "effect/eff_pointget.c"),
            Object(NonMatching, "effect/eff_puniballoon.c"),
            Object(NonMatching, "effect/eff_queen.c"),
            Object(NonMatching, "effect/eff_queen2.c"),
            Object(NonMatching, "effect/eff_rankup.c"),
            Object(NonMatching, "effect/eff_recovery.c"),
            Object(NonMatching, "effect/eff_ripple.c"),
            Object(NonMatching, "effect/eff_sandars.c"),
            Object(NonMatching, "effect/eff_scanning.c"),
            Object(NonMatching, "effect/eff_sheep.c"),
            Object(NonMatching, "effect/eff_sleep.c"),
            Object(NonMatching, "effect/eff_small_star.c"),
            Object(NonMatching, "effect/eff_spark.c"),
            Object(NonMatching, "effect/eff_spirit.c"),
            Object(NonMatching, "effect/eff_splash.c"),
            Object(NonMatching, "effect/eff_stageclear.c"),
            Object(NonMatching, "effect/eff_stardust.c"),
            Object(NonMatching, "effect/eff_starpoint.c"),
            Object(NonMatching, "effect/eff_starstone.c"),
            Object(NonMatching, "effect/eff_syuryou.c"),
            Object(NonMatching, "effect/eff_teresa.c"),
            Object(NonMatching, "effect/eff_toge_flush.c"),
            Object(NonMatching, "effect/eff_toiki.c"),
            Object(NonMatching, "effect/eff_torch.c"),
            Object(NonMatching, "effect/eff_treasure_map.c"),
            Object(NonMatching, "effect/eff_ultra_hammer.c"),
            Object(NonMatching, "effect/eff_updown.c"),
            Object(NonMatching, "effect/eff_uranoko.c"),
        ],
    },
    {
        "lib": "effect_n64",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "effect/n64/eff_akari_charge_n64.c"),
            Object(NonMatching, "effect/n64/eff_akari_pose_n64.c"),
            Object(NonMatching, "effect/n64/eff_akari_sflush_n64.c"),
            Object(NonMatching, "effect/n64/eff_balloon_heiho_n64.c"),
            Object(NonMatching, "effect/n64/eff_balloon_n64.c"),
            Object(NonMatching, "effect/n64/eff_blow_n64.c"),
            Object(NonMatching, "effect/n64/eff_bomb_n64.c"),
            Object(NonMatching, "effect/n64/eff_bomhei_n64.c"),
            Object(NonMatching, "effect/n64/eff_booboo_n64.c"),
            Object(NonMatching, "effect/n64/eff_breath_fire_n64.c"),
            Object(NonMatching, "effect/n64/eff_broken_barrier_n64.c"),
            Object(NonMatching, "effect/n64/eff_bush_n64.c"),
            Object(NonMatching, "effect/n64/eff_butterfly_n64.c"),
            Object(NonMatching, "effect/n64/eff_cloud_n64.c"),
            Object(NonMatching, "effect/n64/eff_coin_n64.c"),
            Object(NonMatching, "effect/n64/eff_confetti_n64.c"),
            Object(NonMatching, "effect/n64/eff_cool_leaf_n64.c"),
            Object(NonMatching, "effect/n64/eff_crystal_n64.c"),
            Object(NonMatching, "effect/n64/eff_dogabon_attack_n64.c"),
            Object(NonMatching, "effect/n64/eff_expbom_n64.c"),
            Object(NonMatching, "effect/n64/eff_explosion_n64.c"),
            Object(NonMatching, "effect/n64/eff_fall_leaf_n64.c"),
            Object(NonMatching, "effect/n64/eff_fire_dust_n64.c"),
            Object(NonMatching, "effect/n64/eff_fire_ring_n64.c"),
            Object(NonMatching, "effect/n64/eff_fire_spark_n64.c"),
            Object(NonMatching, "effect/n64/eff_fireflower_n64.c"),
            Object(NonMatching, "effect/n64/eff_fireworks_n64.c"),
            Object(NonMatching, "effect/n64/eff_flame_n64.c"),
            Object(NonMatching, "effect/n64/eff_flower_n64.c"),
            Object(NonMatching, "effect/n64/eff_freeze_n64.c"),
            Object(NonMatching, "effect/n64/eff_gareki_n64.c"),
            Object(NonMatching, "effect/n64/eff_glass_n64.c"),
            Object(NonMatching, "effect/n64/eff_guruguru_n64.c"),
            Object(NonMatching, "effect/n64/eff_hagetaka_flush_n64.c"),
            Object(NonMatching, "effect/n64/eff_hit_n64.c"),
            Object(NonMatching, "effect/n64/eff_hokori_n64.c"),
            Object(NonMatching, "effect/n64/eff_holography_n64.c"),
            Object(NonMatching, "effect/n64/eff_horao_spell_n64.c"),
            Object(NonMatching, "effect/n64/eff_ice_n64.c"),
            Object(NonMatching, "effect/n64/eff_kameki_tornade_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri10_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri11_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri12_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri1_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri2_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri3_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri4_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri5_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri6_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri7_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri8_n64.c"),
            Object(NonMatching, "effect/n64/eff_kemuri9_n64.c"),
            Object(NonMatching, "effect/n64/eff_kumokumo_chip_n64.c"),
            Object(NonMatching, "effect/n64/eff_kumokumo_n64.c"),
            Object(NonMatching, "effect/n64/eff_lensflare_n64.c"),
            Object(NonMatching, "effect/n64/eff_magic1_n64.c"),
            Object(NonMatching, "effect/n64/eff_magic2_n64.c"),
            Object(NonMatching, "effect/n64/eff_magic3_n64.c"),
            Object(NonMatching, "effect/n64/eff_magic_horao_n64.c"),
            Object(NonMatching, "effect/n64/eff_n64.c"),
            Object(NonMatching, "effect/n64/eff_onpu_n64.c"),
            Object(NonMatching, "effect/n64/eff_opuku_jetw_n64.c"),
            Object(NonMatching, "effect/n64/eff_opuku_jetwrain_n64.c"),
            Object(NonMatching, "effect/n64/eff_opuku_wcurtain_n64.c"),
            Object(NonMatching, "effect/n64/eff_opuku_wgun_n64.c"),
            Object(NonMatching, "effect/n64/eff_opuku_wprotect_n64.c"),
            Object(NonMatching, "effect/n64/eff_packn_bfire_n64.c"),
            Object(NonMatching, "effect/n64/eff_peach_dust_n64.c"),
            Object(NonMatching, "effect/n64/eff_pikkyolo_n64.c"),
            Object(NonMatching, "effect/n64/eff_pokopi_pcharge_n64.c"),
            Object(NonMatching, "effect/n64/eff_pokopi_pipo_n64.c"),
            Object(NonMatching, "effect/n64/eff_pokopi_thunder_n64.c"),
            Object(NonMatching, "effect/n64/eff_pturn_n64.c"),
            Object(NonMatching, "effect/n64/eff_radiation_n64.c"),
            Object(NonMatching, "effect/n64/eff_rappa_n64.c"),
            Object(NonMatching, "effect/n64/eff_recover_heart_n64.c"),
            Object(NonMatching, "effect/n64/eff_release_n64.c"),
            Object(NonMatching, "effect/n64/eff_ripple_n64.c"),
            Object(NonMatching, "effect/n64/eff_rothammer_fail_n64.c"),
            Object(NonMatching, "effect/n64/eff_rothammer_success_n64.c"),
            Object(NonMatching, "effect/n64/eff_rubble_n64.c"),
            Object(NonMatching, "effect/n64/eff_shock_n64.c"),
            Object(NonMatching, "effect/n64/eff_small_star_n64.c"),
            Object(NonMatching, "effect/n64/eff_snow_dust_n64.c"),
            Object(NonMatching, "effect/n64/eff_snow_n64.c"),
            Object(NonMatching, "effect/n64/eff_snowfall_n64.c"),
            Object(NonMatching, "effect/n64/eff_snowman_n64.c"),
            Object(NonMatching, "effect/n64/eff_sstar_n64.c"),
            Object(NonMatching, "effect/n64/eff_stamp_n64.c"),
            Object(NonMatching, "effect/n64/eff_star_power_n64.c"),
            Object(NonMatching, "effect/n64/eff_stardust2_n64.c"),
            Object(NonMatching, "effect/n64/eff_stardust_n64.c"),
            Object(NonMatching, "effect/n64/eff_stone_smoke_n64.c"),
            Object(NonMatching, "effect/n64/eff_sunlight_n64.c"),
            Object(NonMatching, "effect/n64/eff_sweat_n64.c"),
            Object(NonMatching, "effect/n64/eff_thruhammer_n64.c"),
            Object(NonMatching, "effect/n64/eff_thunder_n64.c"),
            Object(NonMatching, "effect/n64/eff_thunderflare_n64.c"),
            Object(NonMatching, "effect/n64/eff_timestamp_n64.c"),
            Object(NonMatching, "effect/n64/eff_vapor_n64.c"),
            Object(NonMatching, "effect/n64/eff_wangflush_n64.c"),
            Object(NonMatching, "effect/n64/eff_water_damage_n64.c"),
            Object(NonMatching, "effect/n64/eff_whirlwind_n64.c"),
        ],
    },
    {
        "lib": "event",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "event/evt_audience.c"),
            Object(NonMatching, "event/evt_badgeshop.c"),
            Object(NonMatching, "event/evt_batstage.c"),
            Object(NonMatching, "event/evt_bero.c"),
            Object(NonMatching, "event/evt_bg.c"),
            Object(NonMatching, "event/evt_cam.c"),
            Object(NonMatching, "event/evt_case.c"),
            Object(NonMatching, "event/evt_cloud.c"),
            Object(NonMatching, "event/evt_damage.c"),
            Object(NonMatching, "event/evt_door.c"),
            Object(NonMatching, "event/evt_eff.c"),
            Object(NonMatching, "event/evt_env.c"),
            Object(NonMatching, "event/evt_ext.c"),
            Object(NonMatching, "event/evt_fade.c"),
            Object(NonMatching, "event/evt_hit.c"),
            Object(NonMatching, "event/evt_img.c"),
            Object(NonMatching, "event/evt_item.c"),
            Object(NonMatching, "event/evt_johoya.c"),
            Object(NonMatching, "event/evt_kinopio.c"),
            Object(NonMatching, "event/evt_lecture.c"),
            Object(NonMatching, "event/evt_light.c"),
            Object(NonMatching, "event/evt_lottery.c"),
            Object(NonMatching, "event/evt_map.c"),
            Object(NonMatching, "event/evt_mario.c"),
            Object(NonMatching, "event/evt_memcard.c"),
            Object(NonMatching, "event/evt_mobj.c"),
            Object(NonMatching, "event/evt_movefloor.c"),
            Object(NonMatching, "event/evt_msg.c"),
            Object(NonMatching, "event/evt_nannpc.c"),
            Object(NonMatching, "event/evt_npc.c"),
            Object(NonMatching, "event/evt_offscreen.c"),
            Object(NonMatching, "event/evt_paper.c"),
            Object(NonMatching, "event/evt_party.c"),
            Object(NonMatching, "event/evt_pouch.c"),
            Object(NonMatching, "event/evt_seq.c"),
            Object(NonMatching, "event/evt_shop.c"),
            Object(NonMatching, "event/evt_snd.c"),
            Object(NonMatching, "event/evt_sub.c"),
            Object(NonMatching, "event/evt_telop.c"),
            Object(NonMatching, "event/evt_twoddisp.c"),
            Object(NonMatching, "event/evt_uranaisi.c"),
            Object(NonMatching, "event/evt_urouro.c"),
            Object(NonMatching, "event/evt_win.c"),
            Object(NonMatching, "event/evt_window.c"),
            Object(NonMatching, "event/evt_yuugijou.c"),
        ],
    },
    {
        "lib": "manager",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "manager/arammgr.c"),
            Object(NonMatching, "manager/cardmgr.c"),
            Object(NonMatching, "manager/dvdmgr.c"),
            Object(NonMatching, "manager/evtmgr.c"),
            Object(NonMatching, "manager/evtmgr_cmd.c"),
            Object(NonMatching, "manager/filemgr.c"),
            Object(NonMatching, "manager/fontmgr.c"),
            Object(NonMatching, "manager/winmgr.c"),
        ],
    },
    {
        "lib": "mario",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "mario/mario.c"),
            Object(NonMatching, "mario/mario_balloon.c"),
            Object(NonMatching, "mario/mario_cam.c"),
            Object(NonMatching, "mario/mario_hit.c"),
            Object(NonMatching, "mario/mario_kemuri.c"),
            Object(NonMatching, "mario/mario_motion.c"),
            Object(NonMatching, "mario/mario_party.c"),
            Object(NonMatching, "mario/mario_pouch.c"),
            Object(NonMatching, "mario/mario_sbr.c"),
            Object(NonMatching, "mario/mariost.c"),
        ],
    },
    {
        "lib": "motion",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "motion/mot_damage.c"),
            Object(NonMatching, "motion/mot_dokan.c"),
            Object(NonMatching, "motion/mot_hammer.c"),
            Object(NonMatching, "motion/mot_hip.c"),
            Object(NonMatching, "motion/mot_jabara.c"),
            Object(NonMatching, "motion/mot_jump.c"),
            Object(NonMatching, "motion/mot_plane.c"),
            Object(NonMatching, "motion/mot_roll.c"),
            Object(NonMatching, "motion/mot_ship.c"),
            Object(NonMatching, "motion/mot_slit.c"),
            Object(NonMatching, "motion/mot_stay.c"),
            Object(NonMatching, "motion/mot_walk.c"),
            Object(NonMatching, "motion/mot_yoshi.c"),
        ],
    },
    {
        "lib": "party",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "party/party.c"),
            Object(NonMatching, "party/party_2.c"),
            Object(NonMatching, "party/party_bomhei.c"),
            Object(NonMatching, "party/party_chuchu.c"),
            Object(NonMatching, "party/party_cloud.c"),
            Object(NonMatching, "party/party_data.c"),
            Object(NonMatching, "party/party_hit.c"),
            Object(NonMatching, "party/party_kuribo.c"),
            Object(NonMatching, "party/party_motion.c"),
            Object(NonMatching, "party/party_move.c"),
            Object(NonMatching, "party/party_nokonoko.c"),
            Object(NonMatching, "party/party_vivian.c"),
            Object(NonMatching, "party/party_yoshi.c"),
        ],
    },
    {
        "lib": "sequence",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "sequence/seq_battle.c"),
            Object(NonMatching, "sequence/seq_e3.c"),
            Object(NonMatching, "sequence/seq_game.c"),
            Object(NonMatching, "sequence/seq_gameover.c"),
            Object(NonMatching, "sequence/seq_load.c"),
            Object(NonMatching, "sequence/seq_logo.c"),
            Object(NonMatching, "sequence/seq_mapchange.c"),
            Object(NonMatching, "sequence/seq_title.c"),
        ],
    },
    {
        "lib": "unit",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "unit/unit_bomzou.c"),
            Object(NonMatching, "unit/unit_koura.c"),
            Object(NonMatching, "unit/unit_mario.c"),
            Object(NonMatching, "unit/unit_object_switch.c"),
            Object(NonMatching, "unit/unit_object_tree.c"),
            Object(NonMatching, "unit/unit_system.c"),
        ],
    },
    {
        "lib": "unit_party",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "unit/party/unit_party_christine.c"),
            Object(NonMatching, "unit/party/unit_party_chuchurina.c"),
            Object(NonMatching, "unit/party/unit_party_clauda.c"),
            Object(NonMatching, "unit/party/unit_party_nokotarou.c"),
            Object(NonMatching, "unit/party/unit_party_sanders.c"),
            Object(NonMatching, "unit/party/unit_party_vivian.c"),
            Object(NonMatching, "unit/party/unit_party_yoshi.c"),
        ],
    },
    {
        "lib": "window",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "host": False,
        "objects": [
            Object(NonMatching, "window/win_badge.c"),
            Object(NonMatching, "window/win_item.c"),
            Object(NonMatching, "window/win_log.c"),
            Object(NonMatching, "window/win_main.c"),
            Object(NonMatching, "window/win_mario.c"),
            Object(NonMatching, "window/win_party.c"),
            Object(NonMatching, "window/win_root.c"),
        ],
    },
    Rel(
        "aaa",
        "src/rel/aaa",
        objects=[
            Object(NonMatching, "aaa.c"),
            Object(NonMatching, "aaa_00.c"),
        ],
    ),
    Rel(
        "aji",
        "src/rel/aji",
        objects=[
            Object(NonMatching, "aji_00.c"),
            Object(NonMatching, "aji_01.c"),
            Object(NonMatching, "aji_02.c"),
            Object(NonMatching, "aji_03.c"),
            Object(NonMatching, "aji_04.c"),
            Object(NonMatching, "aji_05.c"),
            Object(NonMatching, "aji_06.c"),
            Object(NonMatching, "aji_07.c"),
            Object(NonMatching, "aji_08.c"),
            Object(NonMatching, "aji_09.c"),
            Object(NonMatching, "aji_10.c"),
            Object(NonMatching, "aji_11.c"),
            Object(NonMatching, "aji_12.c"),
            Object(NonMatching, "aji_13.c"),
            Object(NonMatching, "aji_14.c"),
            Object(NonMatching, "aji_15.c"),
            Object(NonMatching, "aji_16.c"),
            Object(NonMatching, "aji_17.c"),
            Object(NonMatching, "aji.c"),
            Object(NonMatching, "unit_boss_magnum_battender_mkII.c"),
            Object(NonMatching, "battle_database_aji.c"),
            Object(NonMatching, "aji_18.c"),
            Object(NonMatching, "aji_19.c"),
            Object(NonMatching, "unit_gundan_zako.c"),
            Object(NonMatching, "unit_barriern_z_satellite.c"),
            Object(NonMatching, "unit_barriern_z.c"),
            Object(NonMatching, "unit_gundan_zako_elite.c"),
            Object(NonMatching, "unit_gundan_zako_magician.c"),
            Object(NonMatching, "evt_shuryolight.c"),
            Object(NonMatching, "unit_barriern_custom.c"),
            Object(NonMatching, "unit_barriern_custom_satellite.c"),
            Object(NonMatching, "unit_barriern.c"),
            Object(NonMatching, "unit_barriern_satellite.c"),
        ],
    ),
    Rel(
        "bom",
        "src/rel/bom",
        objects=[
            Object(NonMatching, "bom.c"),
            Object(NonMatching, "bom_00.c"),
            Object(NonMatching, "bom_01.c"),
            Object(NonMatching, "bom_02.c"),
            Object(NonMatching, "bom_04.c"),
            Object(NonMatching, "bom_03.c"),
            Object(NonMatching, "battle_database_bom.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "unit_bllizard.c"),
            Object(NonMatching, "unit_ice_pakkun.c"),
        ],
    ),
    Rel(
        "dmo",
        "src/rel/dmo",
        objects=[
            Object(NonMatching, "dmo_00.c"),
            Object(NonMatching, "dmo.c"),
        ],
    ),
    Rel(
        "dou",
        "src/rel/dou",
        objects=[
            Object(NonMatching, "dou.c"),
            Object(NonMatching, "dou_00.c"),
            Object(NonMatching, "dou_01.c"),
            Object(NonMatching, "dou_02.c"),
            Object(NonMatching, "dou_03.c"),
            Object(NonMatching, "dou_04.c"),
            Object(NonMatching, "dou_05.c"),
            Object(NonMatching, "dou_06.c"),
            Object(NonMatching, "dou_07.c"),
            Object(NonMatching, "dou_08.c"),
            Object(NonMatching, "dou_09.c"),
            Object(NonMatching, "dou_10.c"),
            Object(NonMatching, "dou_11.c"),
            Object(NonMatching, "battle_database_dou.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "unit_bubble.c"),
            Object(NonMatching, "unit_killer.c"),
            Object(NonMatching, "unit_killer_cannon.c"),
            Object(NonMatching, "unit_heavy_bom.c"),
            Object(NonMatching, "unit_hermos.c"),
            Object(NonMatching, "dou_13.c"),
            Object(NonMatching, "dou_12.c"),
            Object(NonMatching, "unit_patamet.c"),
            Object(NonMatching, "evt_lect_dou.c"),
        ],
    ),
    Rel(
        "eki",
        "src/rel/eki",
        objects=[
            Object(NonMatching, "eki.c"),
            Object(NonMatching, "eki_00.c"),
            Object(NonMatching, "eki_01.c"),
            Object(NonMatching, "eki_02.c"),
            Object(NonMatching, "eki_03.c"),
            Object(NonMatching, "eki_04.c"),
            Object(NonMatching, "eki_05.c"),
            Object(NonMatching, "eki_06.c"),
            Object(NonMatching, "battle_database_eki.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "unit_sambo.c"),
            Object(NonMatching, "unit_sambo_mummy.c"),
            Object(NonMatching, "unit_patatogemet.c"),
            Object(NonMatching, "unit_kurokumorn.c"),
            Object(NonMatching, "evt_lect_eki.c"),
        ],
    ),
    Rel(
        "end",
        "src/rel/end",
        objects=[
            Object(NonMatching, "end.c"),
            Object(NonMatching, "end_unknown.c"),
        ],
    ),
    Rel(
        "gon",
        "src/rel/gon",
        objects=[
            Object(NonMatching, "gon.c"),
            Object(NonMatching, "gon_00.c"),
            Object(NonMatching, "gon_01.c"),
            Object(NonMatching, "gon_02.c"),
            Object(NonMatching, "gon_03.c"),
            Object(NonMatching, "gon_04.c"),
            Object(NonMatching, "gon_05.c"),
            Object(NonMatching, "gon_06.c"),
            Object(NonMatching, "gon_07.c"),
            Object(NonMatching, "gon_08.c"),
            Object(NonMatching, "gon_09.c"),
            Object(NonMatching, "gon_10.c"),
            Object(NonMatching, "gon_11.c"),
            Object(NonMatching, "gon_12.c"),
            Object(NonMatching, "gon_bt00.c"),
            Object(NonMatching, "battle_database_gon.c"),
            Object(NonMatching, "unit_boss_gonbaba.c"),
            Object(NonMatching, "unit_honenoko.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "unit_red_honenoko.c"),
            Object(NonMatching, "unit_nokonoko.c"),
            Object(NonMatching, "unit_patakuri.c"),
            Object(NonMatching, "unit_patapata.c"),
            Object(NonMatching, "unit_togekuri.c"),
            Object(NonMatching, "gon_13.c"),
            Object(NonMatching, "evt_lect_gon.c"),
        ],
    ),
    Rel(
        "gor",
        "src/rel/gor",
        objects=[
            Object(NonMatching, "gor.c"),
            Object(NonMatching, "gor_00.c"),
            Object(NonMatching, "gor_01.c"),
            Object(NonMatching, "gor_02.c"),
            Object(NonMatching, "gor_03.c"),
            Object(NonMatching, "gor_04.c"),
            Object(NonMatching, "gor_door.c"),
            Object(NonMatching, "evt_keijiban.c"),
            Object(NonMatching, "battle_database_gor.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "unit_monban.c"),
            Object(NonMatching, "unit_gundan_zako.c"),
            Object(NonMatching, "unit_boss_kanbu1.c"),
            Object(NonMatching, "evt_yuuranking.c"),
            Object(NonMatching, "evt_goryuugijo.c"),
            Object(NonMatching, "gor_irai.c"),
            Object(NonMatching, "gor_10.c"),
            Object(NonMatching, "unit_npc_christine.c"),
            Object(NonMatching, "unit_lecture_christine.c"),
            Object(NonMatching, "unit_lecture_frankli.c"),
            Object(NonMatching, "unit_lecture_frankli_sac.c"),
            Object(NonMatching, "evt_lect_gor.c"),
            Object(NonMatching, "gor_12.c"),
            Object(NonMatching, "gor_11.c"),
        ],
    ),
    Rel(
        "gra",
        "src/rel/gra",
        objects=[
            Object(NonMatching, "gra_00.c"),
            Object(NonMatching, "gra_01.c"),
            Object(NonMatching, "gra_02.c"),
            Object(NonMatching, "gra_03.c"),
            Object(NonMatching, "gra_04.c"),
            Object(NonMatching, "gra_05.c"),
            Object(NonMatching, "gra_06.c"),
            Object(NonMatching, "gra.c"),
            Object(NonMatching, "evt_kagemario.c"),
            Object(NonMatching, "evt_iwamove.c"),
            Object(NonMatching, "battle_database_gra.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "unit_faker_mario_gra.c"),
            Object(NonMatching, "unit_hyper_kuriboo.c"),
            Object(NonMatching, "unit_hyper_patakuri.c"),
            Object(NonMatching, "unit_hyper_togekuri.c"),
            Object(NonMatching, "unit_hyper_sinemon.c"),
            Object(NonMatching, "unit_pansy.c"),
            Object(NonMatching, "unit_twinkling_pansy.c"),
        ],
    ),
    Rel(
        "hei",
        "src/rel/hei",
        objects=[
            Object(NonMatching, "hei.c"),
            Object(NonMatching, "hei_00.c"),
            Object(NonMatching, "hei_01.c"),
            Object(NonMatching, "hei_02.c"),
            Object(NonMatching, "hei_03.c"),
            Object(NonMatching, "hei_04.c"),
            Object(NonMatching, "hei_05.c"),
            Object(NonMatching, "hei_06.c"),
            Object(NonMatching, "hei_07.c"),
            Object(NonMatching, "hei_08.c"),
            Object(NonMatching, "hei_09.c"),
            Object(NonMatching, "hei_10.c"),
            Object(NonMatching, "hei_11.c"),
            Object(NonMatching, "hei_12.c"),
            Object(NonMatching, "hei_13.c"),
            Object(NonMatching, "hei_bt00.c"),
            Object(NonMatching, "battle_database_hei.c"),
            Object(NonMatching, "unit_chorobon.c"),
            Object(NonMatching, "unit_chorobon_gundan.c"),
            Object(NonMatching, "unit_gold_chorobon.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "unit_nokonoko.c"),
            Object(NonMatching, "unit_patakuri.c"),
            Object(NonMatching, "unit_patapata.c"),
            Object(NonMatching, "unit_togekuri.c"),
            Object(NonMatching, "unit_sinemon.c"),
            Object(NonMatching, "unit_sinnosuke.c"),
            Object(NonMatching, "unit_togedaruma.c"),
            Object(NonMatching, "unit_monochrome_sinemon.c"),
            Object(NonMatching, "evt_lect_hei.c"),
        ],
    ),
    Rel(
        "hom",
        "src/rel/hom",
        objects=[
            Object(NonMatching, "hom.c"),
            Object(NonMatching, "hom_00.c"),
            Object(NonMatching, "hom_10.c"),
            Object(NonMatching, "hom_11.c"),
            Object(NonMatching, "hom_12.c"),
        ],
    ),
    Rel(
        "jin",
        "src/rel/jin",
        objects=[
            Object(NonMatching, "jin.c"),
            Object(NonMatching, "jin_00.c"),
            Object(NonMatching, "jin_01.c"),
            Object(NonMatching, "jin_02.c"),
            Object(NonMatching, "jin_03.c"),
            Object(NonMatching, "jin_04.c"),
            Object(NonMatching, "jin_05.c"),
            Object(NonMatching, "jin_06.c"),
            Object(NonMatching, "jin_07.c"),
            Object(NonMatching, "jin_08.c"),
            Object(NonMatching, "jin_09.c"),
            Object(NonMatching, "jin_10.c"),
            Object(NonMatching, "jin_11.c"),
            Object(NonMatching, "evt_kagemario.c"),
            Object(NonMatching, "unit_gullible_christine.c"),
            Object(NonMatching, "unit_gullible_clauda.c"),
            Object(NonMatching, "unit_gullible_nokotarou.c"),
            Object(NonMatching, "unit_gullible_yoshi.c"),
            Object(NonMatching, "battle_database_jin.c"),
            Object(NonMatching, "unit_faker_mario.c"),
            Object(NonMatching, "unit_atmic_teresa.c"),
            Object(NonMatching, "unit_boss_rampell.c"),
            Object(NonMatching, "unit_met.c"),
            Object(NonMatching, "unit_togemet.c"),
            Object(NonMatching, "unit_basabasa.c"),
            Object(NonMatching, "unit_teresa.c"),
        ],
    ),
    Rel(
        "jon",
        "src/rel/jon",
        objects=[
            Object(NonMatching, "jon_06.c"),
            Object(NonMatching, "jon.c"),
            Object(NonMatching, "jon_00.c"),
            Object(NonMatching, "jon_01.c"),
            Object(NonMatching, "jon_02.c"),
            Object(NonMatching, "jon_03.c"),
            Object(NonMatching, "jon_04.c"),
            Object(NonMatching, "jon_05.c"),
            Object(NonMatching, "battle_database_jon.c"),
            Object(NonMatching, "unit_boss_zonbaba.c"),
            Object(NonMatching, "unit_chorobon.c"),
            Object(NonMatching, "unit_hannya.c"),
            Object(NonMatching, "unit_hinnya.c"),
            Object(NonMatching, "unit_honenoko.c"),
            Object(NonMatching, "unit_yami_kuriboo.c"),
            Object(NonMatching, "unit_yami_patakuri.c"),
            Object(NonMatching, "unit_monochrome_sinemon.c"),
            Object(NonMatching, "unit_sambo.c"),
            Object(NonMatching, "unit_monochrome_kurokumorn.c"),
            Object(NonMatching, "unit_yami_togekuri.c"),
            Object(NonMatching, "unit_borodo.c"),
            Object(NonMatching, "unit_jyugem.c"),
            Object(NonMatching, "unit_bomhei.c"),
            Object(NonMatching, "unit_teresa.c"),
            Object(NonMatching, "unit_togezo.c"),
            Object(NonMatching, "unit_yami_noko.c"),
            Object(NonMatching, "unit_hyper_sinemon.c"),
            Object(NonMatching, "unit_patamet.c"),
            Object(NonMatching, "unit_ura_noko.c"),
            Object(NonMatching, "unit_flower_chorobon.c"),
            Object(NonMatching, "unit_yami_pata.c"),
            Object(NonMatching, "unit_heavy_bom.c"),
            Object(NonMatching, "unit_bubble.c"),
            Object(NonMatching, "unit_sambo_mummy.c"),
            Object(NonMatching, "unit_patatogemet.c"),
            Object(NonMatching, "unit_yamitogedaruma.c"),
            Object(NonMatching, "unit_wanwan.c"),
            Object(NonMatching, "unit_twinkling_pansy.c"),
            Object(NonMatching, "unit_togenoko_ace.c"),
            Object(NonMatching, "unit_super_mahorn.c"),
            Object(NonMatching, "unit_sinemon.c"),
            Object(NonMatching, "unit_purple_teresa.c"),
            Object(NonMatching, "unit_phantom.c"),
            Object(NonMatching, "unit_pakkun_flower.c"),
            Object(NonMatching, "unit_mahorn_custom.c"),
            Object(NonMatching, "unit_mahorn.c"),
            Object(NonMatching, "unit_karon.c"),
            Object(NonMatching, "unit_ice_pakkun.c"),
            Object(NonMatching, "unit_hyper_jyugem.c"),
            Object(NonMatching, "unit_hennya.c"),
            Object(NonMatching, "unit_giant_bomb.c"),
            Object(NonMatching, "unit_dokugassun.c"),
            Object(NonMatching, "unit_dark_keeper.c"),
            Object(NonMatching, "unit_burst_wanwan.c"),
            Object(NonMatching, "unit_bllizard.c"),
            Object(NonMatching, "unit_basabasa_chururu.c"),
            Object(NonMatching, "unit_basabasa_green.c"),
            Object(NonMatching, "unit_badge_borodo.c"),
            Object(NonMatching, "unit_piders.c"),
            Object(NonMatching, "unit_hyper_togezo.c"),
            Object(NonMatching, "unit_churantalar.c"),
        ],
    ),
    Rel(
        "kpa",
        "src/rel/kpa",
        objects=[
            Object(NonMatching, "kpa_02.c"),
            Object(NonMatching, "kpa.c"),
            Object(NonMatching, "kpa_00.c"),
            Object(NonMatching, "kpa_01.c"),
            Object(NonMatching, "kpa_06.c"),
            Object(NonMatching, "kpa_03.c"),
            Object(NonMatching, "kpa_04.c"),
            Object(NonMatching, "kpa_05.c"),
            Object(NonMatching, "kpa_07.c"),
        ],
    ),
    Rel(
        "las",
        "src/rel/las",
        objects=[
            Object(NonMatching, "las.c"),
            Object(NonMatching, "las_00.c"),
            Object(NonMatching, "las_01.c"),
            Object(NonMatching, "las_02.c"),
            Object(NonMatching, "las_03.c"),
            Object(NonMatching, "las_04.c"),
            Object(NonMatching, "las_05.c"),
            Object(NonMatching, "las_06.c"),
            Object(NonMatching, "las_07.c"),
            Object(NonMatching, "las_08.c"),
            Object(NonMatching, "las_09.c"),
            Object(NonMatching, "las_10.c"),
            Object(NonMatching, "las_11.c"),
            Object(NonMatching, "las_12.c"),
            Object(NonMatching, "las_13.c"),
            Object(NonMatching, "las_14.c"),
            Object(NonMatching, "las_15.c"),
            Object(NonMatching, "las_16.c"),
            Object(NonMatching, "las_17.c"),
            Object(NonMatching, "las_18.c"),
            Object(NonMatching, "las_19.c"),
            Object(NonMatching, "las_20.c"),
            Object(NonMatching, "las_21.c"),
            Object(NonMatching, "las_22.c"),
            Object(NonMatching, "las_23.c"),
            Object(NonMatching, "las_24.c"),
            Object(NonMatching, "las_25.c"),
            Object(NonMatching, "las_26.c"),
            Object(NonMatching, "las_27.c"),
            Object(NonMatching, "las_28.c"),
            Object(NonMatching, "las_29.c"),
            Object(NonMatching, "battle_database_las.c"),
            Object(NonMatching, "unit_boss_koopa.c"),
            Object(NonMatching, "unit_boss_kamec_obaba.c"),
            Object(NonMatching, "unit_boss_rampell_las.c"),
            Object(NonMatching, "unit_boss_black_peach.c"),
            Object(NonMatching, "unit_black_karon.c"),
            Object(NonMatching, "unit_karon.c"),
            Object(NonMatching, "las_30.c"),
            Object(NonMatching, "unit_boss_batten_leader.c"),
            Object(NonMatching, "unit_boss_batten_satellite.c"),
            Object(NonMatching, "unit_boss_bunbaba.c"),
            Object(NonMatching, "unit_super_killer.c"),
            Object(NonMatching, "unit_super_killer_cannon.c"),
            Object(NonMatching, "unit_super_mahorn.c"),
            Object(NonMatching, "unit_wanwan.c"),
            Object(NonMatching, "unit_basabasa_chururu.c"),
            Object(NonMatching, "evt_shuryolight.c"),
            Object(NonMatching, "unit_phantom.c"),
            Object(NonMatching, "unit_heavy_bom.c"),
            Object(NonMatching, "unit_honenoko.c"),
            Object(NonMatching, "unit_red_honenoko.c"),
            Object(NonMatching, "unit_boss_marilyn_las.c"),
            Object(NonMatching, "unit_boss_majolyne_las.c"),
        ],
    ),
    Rel(
        "moo",
        "src/rel/moo",
        objects=[
            Object(NonMatching, "moo_00.c"),
            Object(NonMatching, "moo_01.c"),
            Object(NonMatching, "moo_02.c"),
            Object(NonMatching, "moo_03.c"),
            Object(NonMatching, "moo_04.c"),
            Object(NonMatching, "moo.c"),
            Object(NonMatching, "battle_database_moo.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "moo_05.c"),
            Object(NonMatching, "moo_06.c"),
            Object(NonMatching, "moo_07.c"),
            Object(NonMatching, "unit_sinemon.c"),
            Object(NonMatching, "unit_barriern_z_satellite.c"),
            Object(NonMatching, "unit_barriern_z.c"),
            Object(NonMatching, "unit_hyper_sinemon.c"),
        ],
    ),
    Rel(
        "mri",
        "src/rel/mri",
        objects=[
            Object(NonMatching, "mri.c"),
            Object(NonMatching, "mri_00.c"),
            Object(NonMatching, "mri_01.c"),
            Object(NonMatching, "mri_02.c"),
            Object(NonMatching, "mri_03.c"),
            Object(NonMatching, "mri_04.c"),
            Object(NonMatching, "mri_05.c"),
            Object(NonMatching, "mri_06.c"),
            Object(NonMatching, "mri_07.c"),
            Object(NonMatching, "mri_08.c"),
            Object(NonMatching, "mri_09.c"),
            Object(NonMatching, "mri_10.c"),
            Object(NonMatching, "mri_11.c"),
            Object(NonMatching, "mri_12.c"),
            Object(NonMatching, "mri_13.c"),
            Object(NonMatching, "mri_14.c"),
            Object(NonMatching, "mri_15.c"),
            Object(NonMatching, "mri_16.c"),
            Object(NonMatching, "punidrv.c"),
            Object(NonMatching, "mri_puni.c"),
            Object(NonMatching, "battle_database_mri.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "unit_boss_magnum_battender.c"),
            Object(NonMatching, "unit_gundan_zako.c"),
            Object(NonMatching, "unit_barriern.c"),
            Object(NonMatching, "unit_piders.c"),
            Object(NonMatching, "unit_barriern_satellite.c"),
            Object(NonMatching, "unit_dokugassun.c"),
            Object(NonMatching, "unit_pakkun_flower.c"),
            Object(NonMatching, "mri_17.c"),
            Object(NonMatching, "mri_20.c"),
            Object(NonMatching, "mri_18.c"),
            Object(NonMatching, "mri_19.c"),
            Object(NonMatching, "unit_boss_kanbu2.c"),
            Object(NonMatching, "unit_monochrome_kurokumorn.c"),
            Object(NonMatching, "unit_monochrome_pakkun.c"),
            Object(NonMatching, "evt_lect_mri.c"),
        ],
    ),
    Rel(
        "muj",
        "src/rel/muj",
        objects=[
            Object(NonMatching, "muj.c"),
            Object(NonMatching, "muj_00.c"),
            Object(NonMatching, "muj_01.c"),
            Object(NonMatching, "muj_02.c"),
            Object(NonMatching, "muj_03.c"),
            Object(NonMatching, "muj_04.c"),
            Object(NonMatching, "muj_05.c"),
            Object(NonMatching, "muj_10.c"),
            Object(NonMatching, "muj_11.c"),
            Object(NonMatching, "muj_12.c"),
            Object(NonMatching, "muj_20.c"),
            Object(NonMatching, "battle_database_muj.c"),
            Object(NonMatching, "unit_boss_cortez.c"),
            Object(NonMatching, "unit_boss_honeduka.c"),
            Object(NonMatching, "unit_boss_cortez_sword.c"),
            Object(NonMatching, "unit_boss_cortez_claw.c"),
            Object(NonMatching, "unit_boss_cortez_rapier.c"),
            Object(NonMatching, "unit_boss_cortez_saber.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "unit_boss_kanbu3.c"),
            Object(NonMatching, "unit_boss_gundan_zako_group1.c"),
            Object(NonMatching, "unit_boss_gundan_zako_group2.c"),
            Object(NonMatching, "unit_boss_gundan_zako_group3.c"),
            Object(NonMatching, "unit_gundan_zako_magician.c"),
            Object(NonMatching, "unit_flower_chorobon.c"),
            Object(NonMatching, "unit_green_chorobon.c"),
            Object(NonMatching, "unit_poison_pakkun.c"),
            Object(NonMatching, "unit_hermos.c"),
            Object(NonMatching, "unit_pakkun_flower.c"),
            Object(NonMatching, "evt_lect_muj.c"),
            Object(NonMatching, "muj_21.c"),
        ],
    ),
    Rel(
        "nok",
        "src/rel/nok",
        objects=[
            Object(NonMatching, "nok.c"),
            Object(NonMatching, "nok_00.c"),
            Object(NonMatching, "nok_01.c"),
            Object(NonMatching, "unit_act_atmic_teresa.c"),
            Object(NonMatching, "unit_act_clauda.c"),
            Object(NonMatching, "unit_act_kinopiko.c"),
            Object(NonMatching, "unit_act_kinopio.c"),
            Object(NonMatching, "unit_act_mario.c"),
            Object(NonMatching, "unit_act_teresa.c"),
            Object(NonMatching, "battle_database_nok.c"),
        ],
    ),
    Rel(
        "pik",
        "src/rel/pik",
        objects=[
            Object(NonMatching, "pik.c"),
            Object(NonMatching, "pik_00.c"),
            Object(NonMatching, "pik_01.c"),
            Object(NonMatching, "pik_02.c"),
            Object(NonMatching, "pik_03.c"),
            Object(NonMatching, "pik_04.c"),
            Object(NonMatching, "battle_database_pik.c"),
            Object(NonMatching, "unit_purple_teresa.c"),
        ],
    ),
    Rel(
        "rsh",
        "src/rel/rsh",
        objects=[
            Object(NonMatching, "rsh.c"),
            Object(NonMatching, "rsh_00.c"),
            Object(NonMatching, "rsh_01.c"),
            Object(NonMatching, "rsh_02.c"),
            Object(NonMatching, "rsh_03.c"),
            Object(NonMatching, "rsh_04.c"),
            Object(NonMatching, "rsh_05.c"),
            Object(NonMatching, "rsh_06.c"),
            Object(NonMatching, "battle_database_rsh.c"),
            Object(NonMatching, "unit_boss_moamoa.c"),
            Object(NonMatching, "rsh_08.c"),
            Object(NonMatching, "rsh_07.c"),
            Object(NonMatching, "unit_boss_moamoa_tentacle_a.c"),
            Object(NonMatching, "unit_boss_moamoa_tentacle_b.c"),
            Object(NonMatching, "unit_boss_moamoa_tentacle_c.c"),
            Object(NonMatching, "unit_boss_moamoa_mouth.c"),
        ],
    ),
    Rel(
        "sys",
        "src/rel/sys",
        objects=[
            Object(NonMatching, "sys.c"),
        ],
    ),
    Rel(
        "tik",
        "src/rel/tik",
        objects=[
            Object(NonMatching, "tik.c"),
            Object(NonMatching, "tik_00.c"),
            Object(NonMatching, "tik_01.c"),
            Object(NonMatching, "tik_02.c"),
            Object(NonMatching, "tik_03.c"),
            Object(NonMatching, "tik_04.c"),
            Object(NonMatching, "tik_05.c"),
            Object(NonMatching, "tik_06.c"),
            Object(NonMatching, "tik_07.c"),
            Object(NonMatching, "tik_08.c"),
            Object(NonMatching, "tik_09.c"),
            Object(NonMatching, "tik_10.c"),
            Object(NonMatching, "tik_13.c"),
            Object(NonMatching, "tik_11.c"),
            Object(NonMatching, "tik_12.c"),
            Object(NonMatching, "unit_boss_gesso.c"),
            Object(NonMatching, "battle_database_tik.c"),
            Object(NonMatching, "tik_14.c"),
            Object(NonMatching, "unit_boss_gesso_right_arm.c"),
            Object(NonMatching, "unit_boss_gesso_left_arm.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "tik_21.c"),
            Object(NonMatching, "tik_15.c"),
            Object(NonMatching, "tik_16.c"),
            Object(NonMatching, "tik_17.c"),
            Object(NonMatching, "tik_18.c"),
            Object(NonMatching, "tik_19.c"),
            Object(NonMatching, "tik_20.c"),
            Object(NonMatching, "unit_hannya.c"),
            Object(NonMatching, "unit_hinnya.c"),
            Object(NonMatching, "unit_patakuri.c"),
            Object(NonMatching, "unit_togekuri.c"),
            Object(NonMatching, "unit_hammer_bros.c"),
            Object(NonMatching, "unit_kamec.c"),
            Object(NonMatching, "unit_patapata.c"),
            Object(NonMatching, "unit_togenoko.c"),
            Object(NonMatching, "unit_nokonoko.c"),
            Object(NonMatching, "evt_lect_tik.c"),
            Object(NonMatching, "unit_lecture_frankli_kuriboo.c"),
            Object(NonMatching, "unit_hennya.c"),
        ],
    ),
    Rel(
        "tou",
        "src/rel/tou",
        objects=[
            Object(NonMatching, "tou.c"),
            Object(NonMatching, "tou_00.c"),
            Object(NonMatching, "tou_01.c"),
            Object(NonMatching, "tou_02.c"),
            Object(NonMatching, "tou_04.c"),
            Object(NonMatching, "tou_05.c"),
            Object(NonMatching, "tou_06.c"),
            Object(NonMatching, "tou_07.c"),
            Object(NonMatching, "tou_08.c"),
            Object(NonMatching, "tou_09.c"),
            Object(NonMatching, "tou_10.c"),
            Object(NonMatching, "tou_11.c"),
            Object(NonMatching, "tou_12.c"),
            Object(NonMatching, "tou_13.c"),
            Object(NonMatching, "tou_20.c"),
            Object(NonMatching, "evt_lect_tou.c"),
        ],
    ),
    Rel(
        "tou2",
        "src/rel/tou2",
        objects=[
            Object(NonMatching, "tou_03.c"),
            Object(NonMatching, "battle_database_tou.c"),
            Object(NonMatching, "unit_boss_macho_gance.c"),
            Object(NonMatching, "unit_boss_champion.c"),
            Object(NonMatching, "tou2.c"),
            Object(NonMatching, "unit_basabasa.c"),
            Object(NonMatching, "unit_bomhei.c"),
            Object(NonMatching, "unit_boomerang_bros.c"),
            Object(NonMatching, "unit_borodo.c"),
            Object(NonMatching, "unit_chorobon.c"),
            Object(NonMatching, "unit_dark_keeper.c"),
            Object(NonMatching, "unit_fire_bros.c"),
            Object(NonMatching, "unit_flower_chorobon.c"),
            Object(NonMatching, "unit_green_chorobon.c"),
            Object(NonMatching, "unit_hammer_bros.c"),
            Object(NonMatching, "unit_hennya.c"),
            Object(NonMatching, "unit_hinnya.c"),
            Object(NonMatching, "unit_honenoko.c"),
            Object(NonMatching, "unit_iron_sinemon.c"),
            Object(NonMatching, "unit_iron_sinemon2.c"),
            Object(NonMatching, "unit_jyugem.c"),
            Object(NonMatching, "unit_kurikuri.c"),
            Object(NonMatching, "unit_piders.c"),
            Object(NonMatching, "unit_sambo.c"),
            Object(NonMatching, "unit_togedaruma.c"),
            Object(NonMatching, "unit_togezo.c"),
            Object(NonMatching, "unit_ura_noko.c"),
            Object(NonMatching, "unit_ura_pata.c"),
            Object(NonMatching, "unit_hannya.c"),
            Object(NonMatching, "unit_hyper_sinnosuke.c"),
            Object(NonMatching, "unit_kamec_green.c"),
            Object(NonMatching, "unit_kamec_red.c"),
            Object(NonMatching, "unit_kamec_white.c"),
            Object(NonMatching, "unit_togenoko_ace.c"),
            Object(NonMatching, "unit_burst_wanwan.c"),
            Object(NonMatching, "unit_hyper_jyugem.c"),
            Object(NonMatching, "unit_hyper_togezo.c"),
            Object(NonMatching, "unit_wanawana.c"),
            Object(NonMatching, "unit_boss_koopa_tou.c"),
            Object(NonMatching, "unit_borodo_king.c"),
            Object(NonMatching, "unit_nokonoko_fighter.c"),
            Object(NonMatching, "unit_patapata_fighter.c"),
            Object(NonMatching, "unit_crimson_togemet.c"),
            Object(NonMatching, "unit_monochrome_kurokumorn.c"),
            Object(NonMatching, "unit_monochrome_pakkun.c"),
        ],
    ),
    Rel(
        "usu",
        "src/rel/usu",
        objects=[
            Object(NonMatching, "usu.c"),
            Object(NonMatching, "usu_00.c"),
            Object(NonMatching, "usu_01.c"),
            Object(NonMatching, "evt_kagemario.c"),
            Object(NonMatching, "evt_lect_usu.c"),
        ],
    ),
    Rel(
        "win",
        "src/rel/win",
        objects=[
            Object(NonMatching, "win_00.c"),
            Object(NonMatching, "win_01.c"),
            Object(NonMatching, "win_02.c"),
            Object(NonMatching, "win_03.c"),
            Object(NonMatching, "win_04.c"),
            Object(NonMatching, "win_05.c"),
            Object(NonMatching, "win.c"),
            Object(NonMatching, "battle_database_win.c"),
            Object(NonMatching, "unit_kuriboo.c"),
            Object(NonMatching, "unit_gundan_zako.c"),
            Object(NonMatching, "unit_dokugassun.c"),
            Object(NonMatching, "unit_pakkun_flower.c"),
            Object(NonMatching, "win_06.c"),
            Object(NonMatching, "unit_boss_vivian.c"),
            Object(NonMatching, "unit_boss_majolyne.c"),
            Object(NonMatching, "unit_boss_marilyn.c"),
            Object(NonMatching, "unit_monochrome_sinemon.c"),
            Object(NonMatching, "unit_monochrome_pakkun.c"),
            Object(NonMatching, "unit_monochrome_kurokumorn.c"),
            Object(NonMatching, "evt_lect_win.c"),
        ],
    ),
    Rel(
        "yuu",
        "src/rel/yuu",
        objects=[
            Object(NonMatching, "yuu_02.c"),
            Object(NonMatching, "yuu_03.c"),
            Object(NonMatching, "yuu.c"),
            Object(NonMatching, "yuu_00.c"),
            Object(NonMatching, "yuu_01.c"),
            Object(NonMatching, "evt_yuuranking.c"),
            Object(NonMatching, "evt_yuutitle.c"),
            Object(NonMatching, "evt_yuucounter.c"),
            Object(NonMatching, "evt_yuuminigame.c"),
            Object(NonMatching, "evt_yuunpc.c"),
        ],
    ),
]

if args.mode == "configure":
    # Write build.ninja and objdiff.json
    generate_build(config)
elif args.mode == "progress":
    # Print progress and write progress.json
    config.progress_each_module = args.verbose
    calculate_progress(config)
else:
    sys.exit("Unknown mode: " + args.mode)
