#include "battle/battle_seq_command.h"


/* AUTO-SWEEP GENERATED STUBS: main/battle/battle_seq_command */
/*
 * Generated by auto_sweep_object.py v2.3.
 * Review before pasting. High-confidence stubs are mechanical target-only patterns;
 * medium/none entries need extra care or manual cleanup.
 */

/* Common externs inferred from target-only wrappers. Skip duplicates already in the .c file. */
extern void BattleMenuDisp_ChangePartySelect_Disp();
extern void BattleMenuDisp_MultiItem_Disp();
extern void BattleMenuDisp_Operation_Disp();
extern void BattleMenuDisp_WeaponSelect_Disp();
extern void BattleMenuDisp_ActSelect_End();
extern void BattleMenuDisp_ChangePartySelect_End();
extern void BattleMenuDisp_MultiItem_End();
extern void BattleMenuDisp_Operation_End();
extern void BattleMenuDisp_WeaponSelect_End();
extern void BattleMenuDisp_ChangePartySelect_Init();
extern void _btlcmd_GetCursorPtr();
extern void BattleMenuDisp_ActSelect_Disp();
extern void* _battleWorkPointer;
extern void _btlcmd_MakeMultiItemTable();
extern void BattleMenuDisp_MultiItem_Init();
extern void _btlcmd_MakeOperationTable();
extern void BattleMenuDisp_Operation_Init();
extern void* pouchGetPtr();
extern void* BattleGetUnitPtr();
extern void* BattleGetPartnerPtr();
extern s32 BtlUnit_GetBodyPartsId();
extern void* BtlUnit_GetPartsPtr();
extern void BtlUnit_SetAnimType();
extern void btl_camera_set_mode();
extern void _btlcmd_MakeSelectWeaponTable();
extern void BattleMenuDisp_WeaponSelect_Init();

/* [high] BattleCommandDisplay_ProtectPartnerSelectMenuEnd: battle command flag clear
 */
void BattleCommandDisplay_ProtectPartnerSelectMenuEnd(void* work) {
    *(u32*)((s32)work + 0x1720) &= ~0x00100000;
}

/* [high] _cursor_init: battle_seq_command cursor zero init
 */
void _cursor_init(void* cursor) {
    *(s32*)((s32)cursor + 0x0) = 0;
    *(s32*)((s32)cursor + 0x4) = 0;
}

/* [high] BattleCommandDisplay_AllEnd: battle command all-end mask clear
 */
void BattleCommandDisplay_AllEnd(void* work) {
    *(u32*)((s32)work + 0x1720) &= 0xFFEEEEEE;
}

/* [high] BattleCommandDisplay_WeaponMultiItemCancelCheckSetup: battle command cancel-check setup stores
 */
void BattleCommandDisplay_WeaponMultiItemCancelCheckSetup(void* work) {
    *(s32*)((s32)work + 0x1C50) = 0;
    *(s32*)((s32)work + 0x1C54) = 0;
    *(s32*)((s32)work + 0x1C58) = 2;
}

/* [high] BattleCommandInit: battle command init field stores
 */
void BattleCommandInit(void* work) {
    *(s32*)((s32)work + 0x171C) = 0;
    *(s32*)((s32)work + 0xEF4) |= 0x80;
}

/* [high] BattleCommandDisplay_ChangePartySelectMenuDisp: battle command r4 display wrapper
 */
void BattleCommandDisplay_ChangePartySelectMenuDisp(void* work, void* menuWork) {
    BattleMenuDisp_ChangePartySelect_Disp(menuWork);
}

/* [high] BattleCommandDisplay_MultiItemMenuDisp: battle command r4 display wrapper
 */
void BattleCommandDisplay_MultiItemMenuDisp(void* work, void* menuWork) {
    BattleMenuDisp_MultiItem_Disp(menuWork);
}

/* [high] BattleCommandDisplay_OperationMenuDisp: battle command r4 display wrapper
 */
void BattleCommandDisplay_OperationMenuDisp(void* work, void* menuWork) {
    BattleMenuDisp_Operation_Disp(menuWork);
}

/* [high] BattleCommandDisplay_WeaponSelectMenuDisp: battle command r4 display wrapper
 */
void BattleCommandDisplay_WeaponSelectMenuDisp(void* work, void* menuWork) {
    BattleMenuDisp_WeaponSelect_Disp(menuWork);
}

/* [high] BattleCommandDisplay_ActMenuEnd: battle command menu-end wrapper and flag clear
 */
void BattleCommandDisplay_ActMenuEnd(void* work) {
    BattleMenuDisp_ActSelect_End(work);
    *(u32*)((s32)work + 0x1720) &= ~0x00000001;
}

/* [high] BattleCommandDisplay_ChangePartySelectMenuEnd: battle command menu-end wrapper and flag clear
 */
void BattleCommandDisplay_ChangePartySelectMenuEnd(void* work) {
    BattleMenuDisp_ChangePartySelect_End(work);
    *(u32*)((s32)work + 0x1720) &= ~0x00001000;
}

/* [high] BattleCommandDisplay_MultiItemMenuEnd: battle command menu-end wrapper and flag clear
 */
void BattleCommandDisplay_MultiItemMenuEnd(void* work) {
    BattleMenuDisp_MultiItem_End(work);
    *(u32*)((s32)work + 0x1720) &= ~0x00000020;
}

/* [high] BattleCommandDisplay_OperationMenuEnd: battle command menu-end wrapper and flag clear
 */
void BattleCommandDisplay_OperationMenuEnd(void* work) {
    BattleMenuDisp_Operation_End(work);
    *(u32*)((s32)work + 0x1720) &= ~0x00000100;
}

/* [high] BattleCommandDisplay_WeaponSelectMenuEnd: battle command menu-end wrapper and flag clear
 */
void BattleCommandDisplay_WeaponSelectMenuEnd(void* work) {
    BattleMenuDisp_WeaponSelect_End(work);
    *(u32*)((s32)work + 0x1720) &= ~0x00000010;
}

/* [medium] BattleCommandDisplay_ChangePartySelectMenuSetup: battle command change-party setup wrapper
 */
void BattleCommandDisplay_ChangePartySelectMenuSetup(void* work, s32 flags) {
    BattleMenuDisp_ChangePartySelect_Init(work, flags);
    *(u32*)((s32)work + 0x1720) |= 0x01001000;
}

/* [medium] BattleCommandDisplay_ActMenuDisp: battle command act-menu display
 */
void BattleCommandDisplay_ActMenuDisp(void* work, void* menuWork) {
    void* cursor;

    _btlcmd_GetCursorPtr((void*)((s32)menuWork + 0x171C), 0xE, &cursor);
    BattleMenuDisp_ActSelect_Disp(menuWork);
}

/* [medium] _commandRestoreRec: battle command restore cursor record
 */
void _commandRestoreRec(void) {
    void* work;

    work = _battleWorkPointer;
    if (*(u8*)((s32)work + 0x1C74) == 0) {
        *(s32*)((s32)work + 0x1C70) = *(s32*)((s32)work + 0x171C);
        return;
    }

    if (*(s32*)((s32)work + 0x1C70) != *(s32*)((s32)work + 0x171C)) {
        return;
    }

    *(s32*)((s32)work + 0x1C70) = 0;
    *(u8*)((s32)work + 0x1C74) = 0;
}

/* [medium] BattleCommandDisplay_MultiItemMenuSetup: battle command multi-item setup wrapper
 */
void BattleCommandDisplay_MultiItemMenuSetup(void* work, s32 flags) {
    _btlcmd_MakeMultiItemTable(work);
    BattleMenuDisp_MultiItem_Init(work, flags);
    *(u32*)((s32)work + 0x1720) |= 0x20;
}

/* [medium] BattleCommandDisplay_OperationMenuSetup: battle command operation setup wrapper
 */
void BattleCommandDisplay_OperationMenuSetup(void* work, s32 flags) {
    _btlcmd_MakeOperationTable(work);
    BattleMenuDisp_Operation_Init(work, flags);
    *(u32*)((s32)work + 0x1720) |= 0x01000100;
}

/* [medium] BattleGetSelectWeapon: battle command selected weapon lookup
 */
s32 BattleGetSelectWeapon(void* work) {
    void* cursor;
    void* base;
    s32 index;

    base = (void*)((s32)work + 0x171C);
    _btlcmd_GetCursorPtr(base, *(s32*)((s32)work + 0x1C5C), &cursor);
    index = *(s32*)cursor;
    return *(s32*)((s32)base + 0x80 + index * 0x1C);
}

/* [medium] _getHammerIconId: pouch level to icon id
 */
s32 _getHammerIconId(void) {
    s32 level;

    level = *(s8*)((s32)pouchGetPtr() + 0x99);

    if (level == 3) {
        goto hammer_lv3;
    }
    if (level >= 3) {
        goto hammer_default;
    }
    if (level >= 2) {
        goto hammer_lv2;
    }
    goto hammer_default;

hammer_lv3:
    return 0xA6;

hammer_lv2:
    return 0xA5;

hammer_default:
    return 0xA4;
}

/* [medium] _getJumpIconId: pouch level to icon id
 */
s32 _getJumpIconId(void) {
    s32 level;

    level = *(s8*)((s32)pouchGetPtr() + 0x98);

    if (level == 3) {
        goto jump_lv3;
    }
    if (level >= 3) {
        goto jump_default;
    }
    if (level >= 2) {
        goto jump_lv2;
    }
    goto jump_default;

jump_lv3:
    return 0xA9;

jump_lv2:
    return 0xA8;

jump_default:
    return 0xA7;
}

/* [medium] BattleCommandDisplay_ProtectPartnerSelectMenuSetup: battle command protect-partner setup
 */
void BattleCommandDisplay_ProtectPartnerSelectMenuSetup(void* work) {
    void* unit;

    unit = BattleGetUnitPtr(work, *(s32*)((s32)work + 0x420));
    BattleGetPartnerPtr(work, unit);
    *(u32*)((s32)work + 0x1720) |= 0x00100000;
    *(u32*)((s32)work + 0x1720) &= ~0x01000000;
}

/* [medium] BattleCommandDisplay_TargetSelectMenuSetup: battle command target-select setup
 */
void BattleCommandDisplay_TargetSelectMenuSetup(void* work) {
    void* unit;
    void* parts;

    unit = BattleGetUnitPtr(work, *(s32*)((s32)work + 0x420));
    *(u32*)((s32)work + 0x1720) |= 0x00010000;

    parts = BtlUnit_GetPartsPtr(unit, BtlUnit_GetBodyPartsId(unit));
    BtlUnit_SetAnimType(parts, 0x28);
}


/* [medium] BattleCommandDisplay_TargetSelectMenuEnd: battle command target-select end
 */
void BattleCommandDisplay_TargetSelectMenuEnd(void* work) {
    void* cursor;
    void* base;

    base = (void*)((s32)work + 0x171C);
    _btlcmd_GetCursorPtr(base, *(s32*)((s32)work + 0x1C5C), &cursor);
    btl_camera_set_mode(0, 0);
    *(u32*)((s32)base + 0x4) &= ~0x00010000;
    *(u32*)((s32)base + 0x4) &= ~0x01000000;
}

/* [medium] BattleCommandDisplay_WeaponSelectMenuSetup: battle command weapon-select setup
 */
void BattleCommandDisplay_WeaponSelectMenuSetup(void* work, s32 cursorId, s32 flags) {
    void* cursor;
    void* base;

    base = (void*)((s32)work + 0x171C);
    _btlcmd_MakeSelectWeaponTable(work);
    _btlcmd_GetCursorPtr(base, cursorId, &cursor);
    BattleMenuDisp_WeaponSelect_Init(work, cursor, (void*)((s32)base + 0x80), flags);
    *(u32*)((s32)base + 0x4) |= 0x01000010;
}


void _btlcmd_MakeSelectWeaponTable() {
}


s32 BattleCommandInput(void* battleWork) {
    return 0;
}


void _btlcmd_MakeActClassTable(void* battleWork) {
}


void _btlcmd_SetAttackEvent(void* unit, void* commandWork) {
}


void BattleCommandDisplay_TargetSelectMenuDisp(s32 param_1, void* battleWork) {
}


s32 BattleCommandDisplay_ActMenuMain(void* battleWork) {
    return 0;
}


void _btlcmd_MakeOperationTable() {
}


s32 BattleCommandDisplay_WeaponSelectMenuMain(void* battleWork, int param_2) {
    return 0;
}


void _btlcmd_MakeMultiItemTable() {
}


s32 BattleCommandDisplay_OperationMenuMain(void* battleWork) {
    return 0;
}


s32 BattleCommandDisplay_MultiItemMenuMain(void* battleWork) {
    return 0;
}


u8 BattleDrawEnemyHP(s32 param_1, int param_2) {
    return 0;
}


s32 BattleCommandDisplay_ChangePartySelectMenuMain(void* battleWork) {
    return 0;
}


s32 _check_present_item(void) {
    return 0;
}


int _btlcmd_MakePartyTable(void* battleWork) {
    return 0;
}


u32 BattleCommandCheckChangePositionEnable(void* battleWork) {
    return 0;
}


u8 BattleDrawEnemyHPBar(float* param_1, int param_2, void* param_3) {
    return 0;
}


int BattleCommandDisplay_WeaponMultiItemCancelCheckMain(void* battleWork) {
    return 0;
}


void BattleCommandDisplay_WeaponMultiItemCancelCheckDisp(s32 param_1, void* battleWork) {
}


u8 BattleCommandDisplay(void* battleWork) {
    return 0;
}


s32 _btlcmd_SelectWeaponDecide(void* battleWork, int param_2, int weaponIndex) {
    return 0;
}


void BattleCommandDisplay_ProtectPartnerSelectMenuDisp(s32 param_1, void* battleWork) {
}


void _btlcmd_UpdateSelectWeaponTable(void* battleWork, int param_2) {
}


void _btlcmd_GetCursorPtr() {
}


s32 BattleCommandAttackAudienceCheck(void) {
    return 0;
}


u8 BattleCommandDisplay_ActMenuSetup(void* battleWork, u32 param_2) {
    return 0;
}


int _btlcmd_CheckWeaponTargetNum(void* battleWork, void* unit, void* weapon) {
    return 0;
}


s32 _get_msg(int param_1) {
    return 0;
}


void* BattleSetConfuseAct(void* battleWork, void* unit) {
    return 0;
}


u32 _battleGetPartyIcon(s32 unitKind) {
    return 0;
}


s32 _check_weapon_type_attack(void* weapon) {
    return 0;
}
