#include "battle/battle_seq_command.h"


/* AUTO-SWEEP GENERATED STUBS: main/battle/battle_seq_command */
/*
 * Generated by auto_sweep_object.py v2.3.
 * Review before pasting. High-confidence stubs are mechanical target-only patterns;
 * medium/none entries need extra care or manual cleanup.
 */

/* Common externs inferred from target-only wrappers. Skip duplicates already in the .c file. */
extern void BattleMenuDisp_ChangePartySelect_Disp();
extern void BattleMenuDisp_MultiItem_Disp();
extern void BattleMenuDisp_Operation_Disp();
extern void BattleMenuDisp_WeaponSelect_Disp();
extern void BattleMenuDisp_ActSelect_End();
extern void BattleMenuDisp_ChangePartySelect_End();
extern void BattleMenuDisp_MultiItem_End();
extern void BattleMenuDisp_Operation_End();
extern void BattleMenuDisp_WeaponSelect_End();
extern void BattleMenuDisp_ChangePartySelect_Init();
extern void _btlcmd_GetCursorPtr();
extern void BattleMenuDisp_ActSelect_Disp();
extern void* _battleWorkPointer;
extern void _btlcmd_MakeMultiItemTable();
extern void BattleMenuDisp_MultiItem_Init();
extern void _btlcmd_MakeOperationTable();
extern void BattleMenuDisp_Operation_Init();
extern void* pouchGetPtr();
extern void* BattleGetUnitPtr();
extern void* BattleGetPartnerPtr();
extern s32 BtlUnit_GetBodyPartsId();
extern void* BtlUnit_GetPartsPtr();
extern void BtlUnit_SetAnimType();
extern void btl_camera_set_mode();
extern void _btlcmd_MakeSelectWeaponTable();
extern void BattleMenuDisp_WeaponSelect_Init();
extern void evtSetValue(void* evt, s32 var, s32 value);
extern const char str_btl_wn_dummy_noitem_802efc28[];

/* [high] BattleCommandDisplay_ProtectPartnerSelectMenuEnd: battle command flag clear
 */
void BattleCommandDisplay_ProtectPartnerSelectMenuEnd(void* work) {
    *(u32*)((s32)work + 0x1720) &= ~0x00100000;
}

/* [high] _cursor_init: battle_seq_command cursor zero init
 */
void _cursor_init(void* cursor) {
    *(s32*)((s32)cursor + 0x0) = 0;
    *(s32*)((s32)cursor + 0x4) = 0;
}

/* [high] BattleCommandDisplay_AllEnd: battle command all-end mask clear
 */
void BattleCommandDisplay_AllEnd(void* work) {
    *(u32*)((s32)work + 0x1720) &= 0xFFEEEEEE;
}

/* [high] BattleCommandDisplay_WeaponMultiItemCancelCheckSetup: battle command cancel-check setup stores
 */
void BattleCommandDisplay_WeaponMultiItemCancelCheckSetup(void* work) {
    *(s32*)((s32)work + 0x1C50) = 0;
    *(s32*)((s32)work + 0x1C54) = 0;
    *(s32*)((s32)work + 0x1C58) = 2;
}

/* [high] BattleCommandInit: battle command init field stores
 */
void BattleCommandInit(void* work) {
    *(s32*)((s32)work + 0x171C) = 0;
    *(s32*)((s32)work + 0xEF4) |= 0x80;
}

/* [high] BattleCommandDisplay_ChangePartySelectMenuDisp: battle command r4 display wrapper
 */
void BattleCommandDisplay_ChangePartySelectMenuDisp(void* work, void* menuWork) {
    BattleMenuDisp_ChangePartySelect_Disp(menuWork);
}

/* [high] BattleCommandDisplay_MultiItemMenuDisp: battle command r4 display wrapper
 */
void BattleCommandDisplay_MultiItemMenuDisp(void* work, void* menuWork) {
    BattleMenuDisp_MultiItem_Disp(menuWork);
}

/* [high] BattleCommandDisplay_OperationMenuDisp: battle command r4 display wrapper
 */
void BattleCommandDisplay_OperationMenuDisp(void* work, void* menuWork) {
    BattleMenuDisp_Operation_Disp(menuWork);
}

/* [high] BattleCommandDisplay_WeaponSelectMenuDisp: battle command r4 display wrapper
 */
void BattleCommandDisplay_WeaponSelectMenuDisp(void* work, void* menuWork) {
    BattleMenuDisp_WeaponSelect_Disp(menuWork);
}

/* [high] BattleCommandDisplay_ActMenuEnd: battle command menu-end wrapper and flag clear
 */
void BattleCommandDisplay_ActMenuEnd(void* work) {
    BattleMenuDisp_ActSelect_End(work);
    *(u32*)((s32)work + 0x1720) &= ~0x00000001;
}

/* [high] BattleCommandDisplay_ChangePartySelectMenuEnd: battle command menu-end wrapper and flag clear
 */
void BattleCommandDisplay_ChangePartySelectMenuEnd(void* work) {
    BattleMenuDisp_ChangePartySelect_End(work);
    *(u32*)((s32)work + 0x1720) &= ~0x00001000;
}

/* [high] BattleCommandDisplay_MultiItemMenuEnd: battle command menu-end wrapper and flag clear
 */
void BattleCommandDisplay_MultiItemMenuEnd(void* work) {
    BattleMenuDisp_MultiItem_End(work);
    *(u32*)((s32)work + 0x1720) &= ~0x00000020;
}

/* [high] BattleCommandDisplay_OperationMenuEnd: battle command menu-end wrapper and flag clear
 */
void BattleCommandDisplay_OperationMenuEnd(void* work) {
    BattleMenuDisp_Operation_End(work);
    *(u32*)((s32)work + 0x1720) &= ~0x00000100;
}

/* [high] BattleCommandDisplay_WeaponSelectMenuEnd: battle command menu-end wrapper and flag clear
 */
void BattleCommandDisplay_WeaponSelectMenuEnd(void* work) {
    BattleMenuDisp_WeaponSelect_End(work);
    *(u32*)((s32)work + 0x1720) &= ~0x00000010;
}

/* [medium] BattleCommandDisplay_ChangePartySelectMenuSetup: battle command change-party setup wrapper
 */
void BattleCommandDisplay_ChangePartySelectMenuSetup(void* work, s32 flags) {
    BattleMenuDisp_ChangePartySelect_Init(work, flags);
    *(u32*)((s32)work + 0x1720) |= 0x01001000;
}

/* [medium] BattleCommandDisplay_ActMenuDisp: battle command act-menu display
 */
void BattleCommandDisplay_ActMenuDisp(void* work, void* menuWork) {
    void* cursor;

    _btlcmd_GetCursorPtr((void*)((s32)menuWork + 0x171C), 0xE, &cursor);
    BattleMenuDisp_ActSelect_Disp(menuWork);
}

/* [medium] _commandRestoreRec: battle command restore cursor record
 */
void _commandRestoreRec(void) {
    void* work;

    work = _battleWorkPointer;
    if (*(u8*)((s32)work + 0x1C74) == 0) {
        *(s32*)((s32)work + 0x1C70) = *(s32*)((s32)work + 0x171C);
        return;
    }

    if (*(s32*)((s32)work + 0x1C70) != *(s32*)((s32)work + 0x171C)) {
        return;
    }

    *(s32*)((s32)work + 0x1C70) = 0;
    *(u8*)((s32)work + 0x1C74) = 0;
}

/* [medium] BattleCommandDisplay_MultiItemMenuSetup: battle command multi-item setup wrapper
 */
void BattleCommandDisplay_MultiItemMenuSetup(void* work, s32 flags) {
    _btlcmd_MakeMultiItemTable(work);
    BattleMenuDisp_MultiItem_Init(work, flags);
    *(u32*)((s32)work + 0x1720) |= 0x20;
}

/* [medium] BattleCommandDisplay_OperationMenuSetup: battle command operation setup wrapper
 */
void BattleCommandDisplay_OperationMenuSetup(void* work, s32 flags) {
    _btlcmd_MakeOperationTable(work);
    BattleMenuDisp_Operation_Init(work, flags);
    *(u32*)((s32)work + 0x1720) |= 0x01000100;
}

/* [medium] BattleGetSelectWeapon: battle command selected weapon lookup
 */
s32 BattleGetSelectWeapon(void* work) {
    void* cursor;
    void* base;
    s32 index;

    base = (void*)((s32)work + 0x171C);
    _btlcmd_GetCursorPtr(base, *(s32*)((s32)work + 0x1C5C), &cursor);
    index = *(s32*)cursor;
    return *(s32*)((s32)base + 0x80 + index * 0x1C);
}

/* [medium] _getHammerIconId: pouch level to icon id
 */
s32 _getHammerIconId(void) {
    s32 level;

    level = *(s8*)((s32)pouchGetPtr() + 0x99);

    if (level == 3) {
        goto hammer_lv3;
    }
    if (level >= 3) {
        goto hammer_default;
    }
    if (level >= 2) {
        goto hammer_lv2;
    }
    goto hammer_default;

hammer_lv3:
    return 0xA6;

hammer_lv2:
    return 0xA5;

hammer_default:
    return 0xA4;
}

/* [medium] _getJumpIconId: pouch level to icon id
 */
s32 _getJumpIconId(void) {
    s32 level;

    level = *(s8*)((s32)pouchGetPtr() + 0x98);

    if (level == 3) {
        goto jump_lv3;
    }
    if (level >= 3) {
        goto jump_default;
    }
    if (level >= 2) {
        goto jump_lv2;
    }
    goto jump_default;

jump_lv3:
    return 0xA9;

jump_lv2:
    return 0xA8;

jump_default:
    return 0xA7;
}

/* [medium] BattleCommandDisplay_ProtectPartnerSelectMenuSetup: battle command protect-partner setup
 */
void BattleCommandDisplay_ProtectPartnerSelectMenuSetup(void* work) {
    void* unit;

    unit = BattleGetUnitPtr(work, *(s32*)((s32)work + 0x420));
    BattleGetPartnerPtr(work, unit);
    *(u32*)((s32)work + 0x1720) |= 0x00100000;
    *(u32*)((s32)work + 0x1720) &= ~0x01000000;
}

/* [medium] BattleCommandDisplay_TargetSelectMenuSetup: battle command target-select setup
 */
void BattleCommandDisplay_TargetSelectMenuSetup(void* work) {
    void* unit;
    void* parts;

    unit = BattleGetUnitPtr(work, *(s32*)((s32)work + 0x420));
    *(u32*)((s32)work + 0x1720) |= 0x00010000;

    parts = BtlUnit_GetPartsPtr(unit, BtlUnit_GetBodyPartsId(unit));
    BtlUnit_SetAnimType(parts, 0x28);
}


/* [medium] BattleCommandDisplay_TargetSelectMenuEnd: battle command target-select end
 */
void BattleCommandDisplay_TargetSelectMenuEnd(void* work) {
    void* cursor;
    void* base;

    base = (void*)((s32)work + 0x171C);
    _btlcmd_GetCursorPtr(base, *(s32*)((s32)work + 0x1C5C), &cursor);
    btl_camera_set_mode(0, 0);
    *(u32*)((s32)base + 0x4) &= ~0x00010000;
    *(u32*)((s32)base + 0x4) &= ~0x01000000;
}

/* [medium] BattleCommandDisplay_WeaponSelectMenuSetup: battle command weapon-select setup
 */
void BattleCommandDisplay_WeaponSelectMenuSetup(void* work, s32 cursorId, s32 flags) {
    void* cursor;
    void* base;

    base = (void*)((s32)work + 0x171C);
    _btlcmd_MakeSelectWeaponTable(work);
    _btlcmd_GetCursorPtr(base, cursorId, &cursor);
    BattleMenuDisp_WeaponSelect_Init(work, cursor, (void*)((s32)base + 0x80), flags);
    *(u32*)((s32)base + 0x4) |= 0x01000010;
}


void _btlcmd_MakeSelectWeaponTable() {
    ;
}


s32 BattleCommandInput(void* battleWork) {
    return 0;
}


void _btlcmd_MakeActClassTable(void* battleWork) {
    ;
}


void _btlcmd_SetAttackEvent(void* unit, void* commandWork) {
    ;
}


void BattleCommandDisplay_TargetSelectMenuDisp(s32 param_1, void* battleWork) {
    ;
}


s32 BattleCommandDisplay_ActMenuMain(void* battleWork) {
    return 0;
}


void _btlcmd_MakeOperationTable() {
    ;
}


s32 BattleCommandDisplay_WeaponSelectMenuMain(void* battleWork, int param_2) {
    return 0;
}


void _btlcmd_MakeMultiItemTable() {
    ;
}


s32 BattleCommandDisplay_OperationMenuMain(void* battleWork) {
    return 0;
}


s32 BattleCommandDisplay_MultiItemMenuMain(void* battleWork) {
    return 0;
}


u8 BattleDrawEnemyHP(s32 param_1, int param_2) {
    return 0;
}


s32 BattleCommandDisplay_ChangePartySelectMenuMain(void* battleWork) {
    return 0;
}


s32 _check_present_item(void) {
    extern s32 BattleAudience_GetPresentItemNo(void);
    extern s32 BattleAudience_GetPresentTargetUnitId(void);
    extern void BattleAudience_SetPresentItemNo(s32);
    extern void BtlUnit_RecoverHp(void*, s16);
    extern void BtlUnit_RecoverFp(void*, s16);
    extern void BtlUnit_GetPos(void*, f32*, f32*, f32*);
    extern s32 BtlUnit_GetHeight(void*);
    extern void effRecoveryEntry(s32, s32, f32, f32, f32);
    void* battleWork;
    void* unit;
    s32 itemNo;
    s32 targetId;
    f32 x;
    f32 y;
    f32 z;

    battleWork = _battleWorkPointer;
    itemNo = BattleAudience_GetPresentItemNo();
    if (itemNo >= 0x153) {
        return 0;
    }

    targetId = BattleAudience_GetPresentTargetUnitId();
    if (targetId < 0 || targetId >= 0x40) {
        return 0;
    }
    unit = BattleGetUnitPtr(battleWork, targetId);

    if (itemNo == 0) {
        return 0;
    }
    if (itemNo == 0x7B) {
        BtlUnit_RecoverHp(unit, 1);
        BtlUnit_GetPos(unit, &x, &y, &z);
        y += *(f32*)((s32)unit + 0x114) * BtlUnit_GetHeight(unit) + 5.0f;
        effRecoveryEntry(0, 1, x, y, z);
        BattleAudience_SetPresentItemNo(0);
        return 0;
    }
    if (itemNo >= 0x7D) {
        goto present_item;
    }
    if (itemNo >= 0x7B) {
        BtlUnit_RecoverFp(unit, 1);
        BtlUnit_GetPos(unit, &x, &y, &z);
        y += *(f32*)((s32)unit + 0x114) * BtlUnit_GetHeight(unit) + 5.0f;
        effRecoveryEntry(1, 1, x, y, z);
        BattleAudience_SetPresentItemNo(0);
        return 0;
    }

present_item:
    if (itemNo < 0 || itemNo >= 0x153) {
        return 0;
    }
    *(u8*)((s32)battleWork + 0x1C74) = 1;
    if (*(s32*)((s32)battleWork + 0x171C) == 0xC || *(s32*)((s32)battleWork + 0x171C) == 0xD) {
        *(u8*)((s32)battleWork + 0x1C74) = 2;
    }
    BattleCommandDisplay_AllEnd(battleWork);
    *(s32*)((s32)battleWork + 0x1C60) = *(s32*)((s32)battleWork + 0x1C5C);
    *(s32*)((s32)battleWork + 0x1C5C) = 0xC;
    *(s32*)((s32)battleWork + 0x171C) = 0x1D;
    return 1;
}

int _btlcmd_MakePartyTable(void* battleWork) {
    return 0;
}


u32 BattleCommandCheckChangePositionEnable(void* battleWork) {
    return 0;
}


u8 BattleDrawEnemyHPBar(float* param_1, int param_2, void* param_3) {
    return 0;
}


int BattleCommandDisplay_WeaponMultiItemCancelCheckMain(void* battleWork) {
    return 0;
}


void BattleCommandDisplay_WeaponMultiItemCancelCheckDisp(s32 param_1, void* battleWork) {
    ;
}


u8 BattleCommandDisplay(void* battleWork) {
    return 0;
}


s32 _btlcmd_SelectWeaponDecide(void* battleWork, int param_2, int weaponIndex) {
    return 0;
}


void BattleCommandDisplay_ProtectPartnerSelectMenuDisp(s32 param_1, void* battleWork) {
    ;
}


void _btlcmd_UpdateSelectWeaponTable(void* battleWork, int param_2) {
    ;
}


void _btlcmd_GetCursorPtr() {
    ;
}


s32 BattleCommandAttackAudienceCheck(void) {
    return 0;
}


u8 BattleCommandDisplay_ActMenuSetup(void* battleWork, u32 param_2) {
    return 0;
}


int _btlcmd_CheckWeaponTargetNum(void* battleWork, void* unit, void* weapon) {
    return 0;
}


s32 _get_msg(void* evt) {
    void* battleWork;
    s32* args;
    s32 dst;
    const char* msg;

    msg = str_btl_wn_dummy_noitem_802efc28;
    battleWork = _battleWorkPointer;
    args = *(s32**)((s32)evt + 0x18);
    dst = args[0];

    switch (*(s32*)((s32)battleWork + 0x1C80)) {
        case 1:
            msg += 0x1A0;
            break;
        case 2:
            msg += 0x1B8;
            break;
        case 4:
            msg += 0x1D0;
            break;
        case 5:
            msg += 0x1F0;
            break;
        case 6:
            msg += 0x214;
            break;
        default:
            msg += 0x230;
            break;
    }

    evtSetValue(evt, dst, (s32)msg);
    return 2;
}


void* BattleSetConfuseAct(void* battleWork, void* unit) {
    return 0;
}


u32 _battleGetPartyIcon(s32 unitKind) {
    return 0;
}


s32 _check_weapon_type_attack(void* weapon) {
    if (weapon == 0) {
        return 0;
    }
    if (*(void**)((s32)weapon + 0x1C) != 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x80) > 0 && *(s8*)((s32)weapon + 0x81) > 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x82) > 0 && *(s8*)((s32)weapon + 0x83) > 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x84) > 0 && *(s8*)((s32)weapon + 0x85) > 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x86) > 0 && *(s8*)((s32)weapon + 0x87) > 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x89) > 0 && *(s8*)((s32)weapon + 0x8A) > 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x8F) > 0 && *(s8*)((s32)weapon + 0x90) > 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x91) > 0 && *(s8*)((s32)weapon + 0x92) > 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x93) > 0 && *(s8*)((s32)weapon + 0x94) > 0 &&
        *(s8*)((s32)weapon + 0x95) < 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x96) > 0 && *(s8*)((s32)weapon + 0x97) > 0 &&
        *(s8*)((s32)weapon + 0x98) < 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x99) > 0 && *(s8*)((s32)weapon + 0x9A) > 0 &&
        *(s8*)((s32)weapon + 0x9B) < 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0x9E) > 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0xA4) > 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0xA5) > 0) {
        return 1;
    }
    if (*(s8*)((s32)weapon + 0xA2) > 0 && *(s8*)((s32)weapon + 0xA3) > 0) {
        return 1;
    }
    return 0;
}

