#pragma once

#include <dolphin/types.h>

void mapErrorEntry(s32 type, char* message);
void* getMapDataDvdRoot(void);
void N_mapDispOff(void);
void N_mapDispOn(void);
void* mapGetWork(void);
s32 mapGetActiveGroup(void);
s32 mapGetJoints(void* data);
void mapInit(void);
void mapCheckAnimation(s32 name, s32* done, f32* frame);
u8 mapPlayAnimationLv(char* name, int mode, int level);
void mapPauseAnimation(char* name);
void mapReStartAnimation(char* name);
void mapPauseAnimationAll(void);
void mapReStartAnimationAll(void);
void mapSetPlayRate(char* name, f32 rate);
void mapLoad(char* name);
void mapUnLoad(void);
void bmapUnLoad(void);
void bmapLoad(char* rankStageName, char* battleStageName);
void mapCalcAnimMatrix(void* dstMtx, void* parentMtx, void* entry, void* track);
void mapMain(void);
u8 test_kururing_mapdisp(s32 cameraId);
void mapDisp(void);
void mapSetMaterialTev(u32 texCount, int drawMode, u32 materialFlag, s32 mtx);
void mapSetMaterialLastStageBlend(u32 flags, void* evtColor, void* value);
void mapSetMaterialFog(void);
void mapSetPaperAmbColor(void* color);
void mapResetPaperAmbColor(void);
u8 mapSetMaterialLight(u32 materialLightFlag, void* position);
void* mapGetMapObj(s32 name);
u8 mapObjFlagOn(char* name, u32 flags);
u8 mapObjFlagOff(char* name, u32 flags);
void mapGrpFlagOn(s32 group, u32 flags);
void mapGrpFlagOff(s32 group, u32 flags);
u8 mapObjSetOffScreen(char* name, char* target);
u8 mapGrpSetOffScreen(char* name, char* target);
void mapObjClearOffScreen(s32 id);
void mapGrpClearOffScreen(s32 id);
u8 mapObjRotate(char* name, f32 x, f32 y, f32 z);
u8 mapObjTranslate(char* name, f32 x, f32 y, f32 z);
u8 mapObjScale(char* name, f32 x, f32 y, f32 z);
u8 mapObjGetPos(char* name, void* position);
void mapSetFog(s32 type, f32 start, f32 end, void* color);
void mapGetFog(void* type, f32* start, f32* end, void* color);
void mapFogOn(void);
void mapFogOff(void);
void mapSetBlend(void* color);
void mapSetBlend2(void* color);
void mapGetBlend(void* color);
void mapGetBlend2(void* color);
void mapBlendOff(void);
void mapBlendOff2(void);
u8 mapObjSetColor(char* name, void* color);
void mapGrpSetColor(s32 group, void* color);
void spline_maketable(s32 count, f32* points, f32* table, f32* out);
void spline_getvalue(float time, float* out, int count, float* values, int times, int slopes);
s32 mapTestXLU(u32 materialFlag, void* value1, void* value2);
void mapSetTevCallback(s32 index, void* callback);
u8 mapObjFlushOn(char* name);
u8 mapObjFlushOff(char* name);
void mapGrpFlushOn(s32 group);
void mapGrpFlushOff(s32 group);
void mapObjSetFlushColor(char* name, u8 r, u8 g, u8 b, u8 a);
void mapGrpSetFlushColor(s32 group, u8 r, u8 g, u8 b, u8 a);
void mapObjGetFlushColor(char* name, void* r, void* g, void* b, void* a);
